import {games,categories,gameById} from './games/registry.js';
import {mountCore} from './games/core.js';
import {mountArcade} from './games/arcade.js';
import {store} from './lib/storage.js';
import {audio} from './lib/audio.js';
import {dailyOrder} from './lib/daily.js';

const $=s=>document.querySelector(s), esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let selectedCategory='All', libraryFilter='All', searchText='', activeGame=null, activeGameId=null, gameSession=null, gameStarted=false, toastTimer=0, daily=null;
audio.configure(store.get().settings);applyTheme();

function applyTheme(){const settings=store.get().settings,light=settings.theme==='light'||(settings.theme==='system'&&window.matchMedia('(prefers-color-scheme: light)').matches);document.body.classList.toggle('light',light);$('#theme-toggle').textContent=light?'☾':'☼';$('#sound-toggle').textContent=settings.sound?'◖))':'◖×';$('#sound-toggle').setAttribute('aria-pressed',String(!!settings.sound));$('#music-toggle').textContent=settings.music?'♫':'♫̸';$('#music-toggle').setAttribute('aria-pressed',String(!!settings.music))}
function toast(message){const t=$('#toast');t.textContent=message;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),1800)}
const setVisible=id=>document.querySelectorAll('.view').forEach(el=>el.hidden=el.id!==`view-${id}`);
function card(game){const data=store.get(),fav=data.favorites.includes(game.id),best=store.best(game.id);return `<article class="game-card" style="--accent:${game.accent}"><div class="card-top"><div class="game-icon">${game.icon}</div><button class="favorite ${fav?'active':''}" data-favorite="${game.id}" aria-label="${fav?'Remove':'Add'} ${esc(game.title)} ${fav?'from':'to'} favorites" title="Favorite">${fav?'★':'☆'}</button></div><h3>${esc(game.title)}</h3><p>${esc(game.description)}</p><div class="card-bottom"><div class="card-tags"><span>${game.category}</span><span>·</span><span>${best?`<span class="best-tag">BEST ${best}</span>`:game.difficulty}</span></div><button class="card-play" data-play="${game.id}">PLAY →</button></div></article>`}
function cards(list,emptyText='No games found yet.'){return list.length?`<div class="card-grid">${list.map(card).join('')}</div>`:`<div class="empty-state">${emptyText}</div>`}
function renderHome(){setVisible('home');const recent=store.get().recent.map(gameById).filter(Boolean).slice(0,4);const featured=games.filter(g=>g.featured).slice(0,4);const cats=categories.filter(x=>x!=='All');$('#view-home').innerHTML=`<section class="hero"><div><div class="eyebrow">A LITTLE GAME BREAK</div><h1>ONE SECOND<br><span>GAMES</span></h1><p>Tiny games. Huge scores.</p><div class="hero-actions"><button class="button primary" data-play="${games[0].id}">⚡ PLAY NOW</button><button class="button secondary" data-route="games">EXPLORE GAMES</button><button class="button ghost" data-action="random">🎲 RANDOM GAME</button></div></div><div class="hero-art" aria-hidden="true"><div class="orbit"><div class="hero-token">1s</div></div><div class="hero-object object-bolt">⚡</div><div class="hero-object object-target">◎</div><div class="hero-object object-die">✦</div><div class="hero-object object-play">▶</div><div class="floating-score one">103 GAMES <b>GO</b></div><div class="floating-score two">↗ BEAT YOUR BEST</div></div></section>
<section class="section"><div class="section-head"><div><div class="eyebrow">SAME CHALLENGE FOR EVERYONE</div><h2>Daily Challenge</h2></div><span class="mono">${store.day()}</span></div><div class="daily-card"><div><span class="eyebrow">TODAY’S CHALLENGE</span><h2>10 games. One daily score.</h2><p>Play today’s seeded lineup and see how far your best run takes you.</p><div class="daily-meta"><span>🎮 10 games</span><span>🏆 Personal best: ${store.get().daily[store.day()]||0}</span><span>🔥 ${store.get().streak.days||0} day streak</span></div><div class="daily-progress"><span style="width:${(store.get().daily[store.day()]||0)?'100%':'0%'}"></span></div></div><div class="daily-action"><button class="button primary" data-action="daily">START CHALLENGE →</button></div></div></section>
<section class="section"><div class="section-head"><div><div class="eyebrow">JUMP RIGHT IN</div><h2>Browse by mood</h2></div><a class="text-link" href="#games">View all games →</a></div><div class="category-row">${cats.map(c=>`<button class="chip" data-home-category="${c}">${categoryIcon(c)} ${c}</button>`).join('')}</div></section>
<section class="section"><div class="section-head"><div><div class="eyebrow">CROWD FAVORITES</div><h2>Popular games</h2></div><a class="text-link" href="#games">Full library →</a></div>${cards(featured)}</section>
${recent.length?`<section class="section"><div class="section-head"><div><div class="eyebrow">PICK UP WHERE YOU LEFT OFF</div><h2>Recently played</h2></div></div>${cards(recent)}</section>`:''}
<div class="ad-slot" aria-label="Advertisement placement reserved for future use">ADVERTISEMENT</div><section class="section"><div class="section-head"><div><div class="eyebrow">NO ACCOUNTS · NO DOWNLOADS</div><h2>Ready for another round?</h2></div><button class="button primary" data-action="random">🎲 RANDOM GAME</button></div>${cards(games.slice(20,24))}</section>`;}
function categoryIcon(cat){return {Reaction:'⚡',Memory:'🧠',Accuracy:'🎯',Math:'➗',Vision:'👀',Speed:'⌨️',Luck:'🍀',Logic:'🧩',Arcade:'🎮',Fun:'😂'}[cat]||'🎮'}
function renderGames(){setVisible('games');document.title='Games | One Second Games';document.querySelector('meta[name="description"]').content='Browse quick, free browser games by category. No account required.';const filtered=games.filter(g=>(selectedCategory==='All'||g.category===selectedCategory)&&(!searchText||`${g.title} ${g.description} ${g.category}`.toLowerCase().includes(searchText.toLowerCase()))&&(libraryFilter==='All'||(libraryFilter==='Favorites'?store.get().favorites.includes(g.id):libraryFilter==='Recently played'?store.get().recent.includes(g.id):libraryFilter==='Featured'?g.featured:libraryFilter==='New'?games.indexOf(g)>=20:true)));$('#view-games').innerHTML=`<div class="page-title"><div class="eyebrow">THE GAME LIBRARY · ${games.length} PLAYABLE GAMES</div><h1>Find your next favorite.</h1><p>Quick rounds, instant rematches, and a personal best worth chasing.</p></div><div class="library-tools"><label class="search-wrap"><span>⌕</span><input id="game-search" type="search" placeholder="Search games…" value="${esc(searchText)}" aria-label="Search games"></label><button class="button secondary" data-action="random">🎲 RANDOM GAME</button></div><div class="library-filters">${['All','Featured','New','Recently played','Favorites'].map(f=>`<button class="chip ${libraryFilter===f?'active':''}" data-filter="${f}">${f}</button>`).join('')}</div><div class="category-row" style="margin-bottom:20px">${categories.map(c=>`<button class="chip ${selectedCategory===c?'active':''}" data-category="${c}">${c==='All'?'✳':categoryIcon(c)} ${c}</button>`).join('')}</div>${cards(filtered,libraryFilter==='Favorites'?'No favorites yet. Tap ☆ on any game card to save it.':'No games match that search.')}`;$('#game-search').addEventListener('input',e=>{searchText=e.target.value;const pos=e.target.selectionStart;renderGames();const input=$('#game-search');input.focus();input.setSelectionRange(pos,pos)})}
function renderStats(){setVisible('stats');document.title='Your Stats | One Second Games';document.querySelector('meta[name="description"]').content='Review your local personal bests, play streak, and favorite games.';const d=store.get(),played=d.stats.played,entries=Object.entries(d.scores);const bestGame=entries.slice().sort((a,b)=>b[1].best-a[1].best)[0],sum=entries.reduce((a,[,s])=>a+s.totalScore,0),playedBy=entries.reduce((a,[id,s])=>a+s.plays,0);const average=playedBy?Math.round(sum/playedBy):0,categoryTotals=games.reduce((out,g)=>{const plays=d.scores[g.id]?.plays||0;if(plays)out[g.category]=(out[g.category]||0)+plays;return out},{});const bestReaction=d.stats.bestReactionTime||0;$('#view-stats').innerHTML=`<div class="page-title"><div class="eyebrow">YOUR LOCAL GAME HISTORY</div><h1>Stats that stay yours.</h1><p>Stored in this browser. No account, no leaderboard, no backend.</p></div><div class="stats-grid"><div class="stat-card"><strong>${played}</strong><span>Games completed</span></div><div class="stat-card"><strong>${formatTime(d.stats.totalMs)}</strong><span>Time played</span></div><div class="stat-card"><strong>${d.streak.days||0} days</strong><span>Daily streak</span></div><div class="stat-card"><strong>${d.stats.perfect}</strong><span>Perfect runs</span></div><div class="stat-card"><strong>${average}</strong><span>Average score</span></div><div class="stat-card"><strong>${bestGame?esc(gameById(bestGame[0])?.title||'—'):'—'}</strong><span>Top personal best</span></div><div class="stat-card"><strong>${bestReaction?`${bestReaction} ms`:'—'}</strong><span>Best reaction time</span></div><div class="stat-card"><strong>${d.favorites.length?esc(gameById(d.favorites[0])?.title||'—'):'—'}</strong><span>Favorite game (${d.favorites.length} saved)</span></div></div><section class="section"><div class="section-head"><div><div class="eyebrow">BY CATEGORY</div><h2>Games completed by category</h2></div></div>${Object.keys(categoryTotals).length?`<div class="stats-grid">${Object.entries(categoryTotals).map(([category,count])=>`<div class="stat-card"><strong>${count}</strong><span>${category}</span></div>`).join('')}</div>`:`<div class="empty-state">Play a few rounds to see your category mix.</div>`}</section><section class="section"><div class="section-head"><div><div class="eyebrow">PERSONAL BESTS</div><h2>Your game history</h2></div><button class="button ghost" data-action="clear-stats">RESET STATS</button></div>${entries.length?`<div class="card-grid">${entries.sort((a,b)=>b[1].best-a[1].best).map(([id,s])=>{const g=gameById(id);return g?`<article class="stat-card"><span>${g.icon} ${esc(g.title)}</span><strong>${s.best}</strong><span>${s.plays} plays</span></article>`:''}).join('')}</div>`:'<div class="empty-state">Your scores will show up here after your first game.</div>'}</section>`}
function formatTime(ms){const m=Math.floor(ms/60000),s=Math.floor(ms/1000)%60;return m?`${m}m ${s}s`:`${s}s`}
function showGameShell(game){setVisible('game');document.title=`${game.title} | One Second Games`;document.querySelector('meta[name="description"]').content=`${game.description} Play ${game.title} free in your browser at One Second Games.`;$('#view-game').innerHTML=`<div class="game-shell"><div class="game-head"><div class="game-title"><div class="game-icon" style="background:${game.accent}24">${game.icon}</div><div><h1>${esc(game.title)}</h1><p>${esc(game.description)}</p></div></div><button class="button ghost" data-action="exit">← GAMES</button></div><div class="game-panel" id="game-panel"></div><div class="section-head" style="margin:14px 3px 0"><span class="mono">${game.category.toUpperCase()} · ${game.difficulty.toUpperCase()}</span><button class="text-link" data-action="music-label">♫ MUSIC ${store.get().settings.music?'ON':'OFF'}</button></div></div>`}
function launchGame(id, dailyState=null){const game=gameById(id);if(!game)return;clearSession();activeGame=game;activeGameId=id;daily=dailyState;store.played(id);showGameShell(game);const panel=$('#game-panel');const finish=result=>{if(activeGameId!==id)return;audio.stop();gameSession=null;gameStarted=false;const oldBest=store.best(id);store.record(game,result);const newBest=result.score>oldBest;renderResult(game,result,{oldBest,newBest,dailyState})};gameSession=(game.category==='Arcade'?mountArcade:mountCore)({panel,game,finish,sound:name=>audio.effect(name),onStart:category=>{gameStarted=true;audio.start(category)}})}
function clearSession(){if(gameSession){gameSession.cleanup();gameSession=null}audio.stop();gameStarted=false;activeGame=null;activeGameId=null}
function renderResult(game,result,{oldBest,newBest,dailyState}){setVisible('game');const best=store.best(game.id),dailyTotal=dailyState?dailyState.total+result.score:null;let nextDaily=dailyState?dailyState.index+1:0;const isLast=dailyState&&nextDaily>=dailyState.ids.length;if(dailyState&&!isLast)daily={...dailyState,index:nextDaily,total:dailyTotal};else daily=null;if(dailyState&&isLast)store.dailyBest(dailyState.day,dailyTotal);const message=newBest?'NEW PERSONAL BEST! 🔥':result.perfect?'PERFECT RUN! ✨':result.reactionTime?`Your reaction: ${result.reactionTime} ms`:`${Math.max(0,best-result.score)} points from your best. Keep going!`;const nextId=game.id;$('#view-game').innerHTML=`<div class="game-shell"><div class="game-head"><div class="game-title"><div class="game-icon">${game.icon}</div><div><h1>${esc(game.title)}</h1><p>Round complete</p></div></div><button class="button ghost" data-action="exit">← GAMES</button></div><div class="game-panel"><div class="result-card"><h2>${dailyState&&isLast?'DAILY CHALLENGE COMPLETE':'GAME OVER'}</h2><div class="result-score">${result.score}</div><div class="result-message">${newBest?'NEW BEST! 🔥':message}</div><p class="muted">${dailyState&&isLast?`DAILY SCORE ${dailyTotal} · DAILY BEST ${Math.max(dailyTotal,store.get().daily[dailyState.day]||0)}`:dailyState?`DAILY CHALLENGE · GAME ${dailyState.index+1} OF 10`:`${esc(game.description)}`}</p><div class="result-meta"><div class="result-stat"><strong>${best}</strong><span>Personal best</span></div>${result.correct!==undefined?`<div class="result-stat"><strong>${result.correct}${result.rounds?` / ${result.rounds}`:''}</strong><span>Correct</span></div>`:''}${result.reactionTime?`<div class="result-stat"><strong>${result.reactionTime} ms</strong><span>Avg reaction</span></div>`:''}<div class="result-stat"><strong>${formatTime(result.elapsed||0)}</strong><span>Time</span></div></div><div class="result-actions"><button class="button primary" data-action="again" data-id="${game.id}">PLAY AGAIN ↻</button><button class="button secondary" data-action="next" data-id="${nextId}">${dailyState&&!isLast?'NEXT DAILY GAME →':'NEXT GAME →'}</button><button class="button ghost" data-action="share" data-game="${game.id}" data-score="${result.score}">↗ SHARE RESULT</button></div></div></div>${dailyState&&!isLast?`<div class="daily-progress"><span style="width:${(dailyState.index+1)*10}%"></span></div>`:''}<div class="section"><div class="section-head"><div><div class="eyebrow">ONE MORE ROUND?</div><h2>Try another quick game</h2></div><a class="text-link" href="#games">All games →</a></div>${cards(games.filter(g=>g.id!==game.id).sort(()=>Math.random()-.5).slice(0,4))}</div></div>`;}
function beginDaily(){const day=store.day(),ids=dailyOrder(day);daily={day,ids,index:0,total:0};launchGame(ids[0],daily)}
function nextGame(){if(daily){const state={...daily};launchGame(state.ids[state.index],state)}else{let list=games.filter(g=>g.id!==activeGame?.id);launchGame(list[Math.floor(Math.random()*list.length)]?.id||games[0].id)}}
async function share(gameId,score){const game=gameById(gameId);const text=`I scored ${score} on ${game?.title||'One Second Games'} ${game?.icon||'🎮'}\nCan you beat me?`;try{if(navigator.share){await navigator.share({title:'One Second Games',text,url:`${location.href.split('#')[0]}#games/${gameId}`})}else if(navigator.clipboard){await navigator.clipboard.writeText(`${text}\n${location.href.split('#')[0]}#games/${gameId}`);toast('Result copied to clipboard')}else{const ta=document.createElement('textarea');ta.value=text;document.body.append(ta);ta.select();document.execCommand('copy');ta.remove();toast('Result copied')}}catch(e){if(e.name!=='AbortError')toast('Could not share from this browser')}}
function setRoute(hash){if(hash.startsWith('#games/')){const id=decodeURIComponent(hash.slice(7));launchGame(id);return}if(hash==='#games'){renderGames();return}if(hash==='#stats'){renderStats();return}clearSession();document.title='One Second Games — 103 Quick Free Browser Games';document.querySelector('meta[name="description"]').content='Play 103 quick, free browser games for reaction, memory, accuracy, math, logic and arcade fun. No download or account needed.';renderHome()}
document.addEventListener('click',e=>{const t=e.target.closest('[data-play],[data-route],[data-action],[data-filter],[data-category],[data-home-category],[data-favorite]');if(!t)return;if(t.dataset.play){e.preventDefault();location.hash=`games/${t.dataset.play}`}else if(t.dataset.route){e.preventDefault();location.hash=t.dataset.route}else if(t.dataset.homeCategory){selectedCategory=t.dataset.homeCategory;libraryFilter='All';location.hash='games'}else if(t.dataset.category){selectedCategory=t.dataset.category;renderGames()}else if(t.dataset.filter){libraryFilter=t.dataset.filter;renderGames()}else if(t.dataset.favorite){const added=store.favorite(t.dataset.favorite);t.classList.toggle('active',added);t.textContent=added?'★':'☆';t.setAttribute('aria-label',`${added?'Remove':'Add'} ${gameById(t.dataset.favorite)?.title} ${added?'from':'to'} favorites`)}else if(t.dataset.action){const a=t.dataset.action;if(a==='random'){const pool=games.filter(g=>selectedCategory==='All'||g.category===selectedCategory);location.hash=`games/${pool[Math.floor(Math.random()*pool.length)].id}`}if(a==='daily')beginDaily();if(a==='exit'){daily=null;location.hash='games'}if(a==='again')launchGame(t.dataset.id);if(a==='next')nextGame();if(a==='share')share(t.dataset.game,t.dataset.score);if(a==='music-label')$('#music-toggle').click();if(a==='clear-stats'){store.update(d=>{d.scores={};d.stats={played:0,totalMs:0,perfect:0,bestReactionTime:0};d.recent=[];d.streak={lastDay:'',days:0};d.daily={}});renderStats();toast('Local statistics reset')}}});
$('#theme-toggle').onclick=()=>{store.update(d=>d.settings.theme=document.body.classList.contains('light')?'dark':'light');applyTheme()};$('#sound-toggle').onclick=()=>{store.update(d=>d.settings.sound=!d.settings.sound);audio.configure(store.get().settings);applyTheme();toast(`Effects ${store.get().settings.sound?'on':'off'}`)};$('#music-toggle').onclick=()=>{store.update(d=>d.settings.music=!d.settings.music);audio.configure(store.get().settings);audio.setMusic(store.get().settings.music);if(store.get().settings.music&&gameStarted&&activeGame)audio.start(activeGame.category);applyTheme();toast(`Music ${store.get().settings.music?'on':'off'}`)};
window.matchMedia('(prefers-color-scheme: light)').addEventListener('change',()=>{if(store.get().settings.theme==='system')applyTheme()});
window.addEventListener('hashchange',()=>setRoute(location.hash));document.querySelectorAll('.main-nav a').forEach(a=>a.addEventListener('click',()=>{document.querySelectorAll('.main-nav a').forEach(n=>n.classList.remove('active'));a.classList.add('active')}));
document.addEventListener('visibilitychange',()=>{if(document.hidden&&gameSession&&activeGame&&gameStarted){const current=activeGame;gameSession.cleanup();gameSession=null;audio.stop();const panel=$('#game-panel');if(panel){panel.classList.remove('playing');panel.innerHTML=`<div class="eyebrow">SESSION PAUSED</div><h2>Welcome back.</h2><p class="instructions">We ended that round when you left the tab so your score stays fair.</p><button class="button primary" data-action="again" data-id="${current.id}">RESTART GAME</button>`}}});
if('serviceWorker' in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./sw.js').catch(()=>{});
setRoute(location.hash||'#home');
