import {rand,pick} from './common.js';

const arenaMarkup=`<div class="target-arena" style="height:290px"></div>`;
function distanceScore(event,target){const r=target.getBoundingClientRect(),dx=event.clientX-(r.left+r.width/2),dy=event.clientY-(r.top+r.height/2),d=Math.min(1,Math.hypot(dx,dy)/(Math.min(r.width,r.height)/2));return Math.round((1-d)*1000)}

export function playAccuracy(mode,c){
 const {panel,html,later,every,finishOnce,sound}=c;
 if(!['tinyTarget','movingBullseye','threeShots','perfectCenter','targetRain','oneShot','safeZone','avoidRed','precisionLine'].includes(mode))return false;
 if(['tinyTarget','movingBullseye','threeShots'].includes(mode)){
   let round=0,total=0,hits=0;const moving=mode==='movingBullseye',tiny=mode==='tinyTarget',shots=mode==='threeShots'?3:moving?3:5;
   const next=()=>{if(round>=shots)return finishOnce(Math.round(total/shots),{accuracy:Math.round(total/shots),shots,perfect:total/shots>950});round++;const size=tiny?Math.max(24,76-round*10):moving?72:88;
     html(`<div class="game-hud"><span>${mode==='threeShots'?'SHOT':'TARGET'} ${round} / ${shots}</span><span>SCORE ${Math.round(total)}</span></div><div class="prompt-label">${tiny?'TARGETS SHRINK EACH ROUND':moving?'TRACK THE BULLSEYE':'THREE SHOTS · MAKE THEM COUNT'}</div>${arenaMarkup}`);
     const area=panel.querySelector('.target-arena'),target=document.createElement('button');target.className='target';target.style.width=`${size}px`;target.style.height=`${size}px`;target.style.background='radial-gradient(circle,var(--lime) 0 9%,#cf536a 10% 23%,var(--lime) 24% 40%,#cf536a 41% 57%,var(--lime) 58%)';target.setAttribute('aria-label','Accuracy target');area.append(target);
     const place=()=>{target.style.left=`${rand(Math.max(1,area.clientWidth-size))}px`;target.style.top=`${rand(Math.max(1,area.clientHeight-size))}px`};place();let mover=0;if(moving)mover=every(place,580);
     const shoot=e=>{const pts=distanceScore(e,target);total+=pts;hits++;sound(pts>550?'success':'tap');if(hits>=shots)finishOnce(Math.round(total/shots),{accuracy:Math.round(total/shots),shots,perfect:total/shots>950});else later(next,140)};
     if(mode==='threeShots'){area.onclick=shoot}else{target.onclick=e=>{e.stopPropagation();total+=distanceScore(e,target);sound('success');if(mover)clearInterval(mover);later(next,140)}}
   };next();return true;
 }
 if(mode==='oneShot'){
   html(`<div class="prompt-label">ONE CLICK · ONE SCORE</div>${arenaMarkup}<p class="instructions">Tap anywhere in the arena. Distance from the bullseye sets your score.</p>`);const a=panel.querySelector('.target-arena'),t=document.createElement('div');t.style.cssText='position:absolute;width:74px;height:74px;border-radius:50%;background:radial-gradient(circle,var(--lime) 0 8%,#cf536a 9% 20%,var(--lime) 21% 38%,#cf536a 39% 53%,var(--lime) 54%)';t.style.left=`${rand(Math.max(1,a.clientWidth-80))}px`;t.style.top=`${rand(Math.max(1,a.clientHeight-80))}px`;a.append(t);a.onclick=e=>{const pts=distanceScore(e,t);finishOnce(pts,{accuracy:pts,shots:1,perfect:pts>950})};return true;
 }
 if(mode==='perfectCenter'||mode==='precisionLine'){
   const lineMode=mode==='precisionLine';let pos=0,dir=1,raf=0,zoneStart=lineMode?25+rand(45):45,zoneWidth=lineMode?8:10,active=true;
   html(`<div class="prompt-label">STOP INSIDE THE ${lineMode?'HIGHLIGHT':'CENTER'}</div><div style="position:relative;width:min(570px,100%);height:56px;background:var(--panel-2);border:1px solid var(--line);border-radius:14px;margin:28px 0;overflow:hidden"><div style="position:absolute;left:${zoneStart}%;width:${zoneWidth}%;height:100%;background:#ceff5945;border-left:2px solid var(--lime);border-right:2px solid var(--lime)"></div><div id="sweep-marker" style="position:absolute;top:0;left:0;width:5px;height:100%;background:var(--ink);box-shadow:0 0 15px var(--ink)"></div></div><button class="button primary" id="stop-line">STOP MARKER</button><p class="instructions">The marker moves back and forth. Stop it inside the scoring zone.</p>`);
   const marker=panel.querySelector('#sweep-marker'),button=panel.querySelector('#stop-line');let last=performance.now();const tick=now=>{if(!active)return;const dt=Math.min(32,now-last);last=now;pos+=dir*dt*(lineMode?0.095:0.075);if(pos>99){pos=99;dir=-1}if(pos<0){pos=0;dir=1}marker.style.left=`${pos}%`;raf=requestAnimationFrame(tick)};raf=requestAnimationFrame(tick);button.onclick=()=>{active=false;cancelAnimationFrame(raf);const center=zoneStart+zoneWidth/2,diff=Math.abs(pos-center),inside=pos>=zoneStart&&pos<=zoneStart+zoneWidth;const score=inside?Math.max(0,1000-Math.round(diff*25)):Math.max(0,300-Math.round(diff*14));finishOnce(score,{accuracy:Math.round(score),perfect:inside&&diff<1})};c.setCleanup(()=>{active=false;cancelAnimationFrame(raf)});return true;
 }
 if(mode==='safeZone'){
   let round=0,score=0,pos=0,dir=1,raf=0,active=true,last=performance.now(),zoneStart=20+rand(60),zoneWidth=20;
   const next=()=>{if(round>=3)return finishOnce(Math.round(score/3),{correct:round,accuracy:Math.round(score/3),rounds:3,perfect:score/3>900});round++;zoneWidth=Math.max(7,20-round*4);zoneStart=rand(100-zoneWidth);pos=0;dir=1;last=performance.now();html(`<div class="game-hud"><span>ZONE ${round} / 3</span><span>SAFE WIDTH ${zoneWidth}%</span></div><div style="position:relative;width:min(570px,100%);height:48px;background:var(--panel-2);border-radius:12px;overflow:hidden;margin:25px 0"><div style="position:absolute;left:${zoneStart}%;width:${zoneWidth}%;height:100%;background:#ceff5955;border-inline:2px solid var(--lime)"></div><div id="safe-marker" style="position:absolute;left:0;top:0;width:7px;height:100%;background:var(--ink)"></div></div><button class="button primary" id="safe-stop">STOP IN SAFE ZONE</button>`);const marker=panel.querySelector('#safe-marker');const tick=now=>{if(!active)return;const dt=Math.min(32,now-last);last=now;pos+=dir*dt*.12;if(pos>99){pos=99;dir=-1}if(pos<0){pos=0;dir=1}marker.style.left=`${pos}%`;raf=requestAnimationFrame(tick)};active=true;raf=requestAnimationFrame(tick);panel.querySelector('#safe-stop').onclick=()=>{active=false;cancelAnimationFrame(raf);const inZone=pos>=zoneStart&&pos<=zoneStart+zoneWidth;if(inZone){score+=Math.round(1000-(Math.abs(pos-zoneStart-zoneWidth/2)*20));sound('success')}else sound('fail');later(next,200)}};next();c.setCleanup(()=>{active=false;cancelAnimationFrame(raf)});return true;
 }
 if(mode==='targetRain'){
   let hits=0;const end=performance.now()+10000;html(`<div class="game-hud"><span id="rain-left">10.0s</span><span id="rain-score">HITS 0</span></div><div class="prompt-label">TARGET RAIN · CATCH THEM</div>${arenaMarkup}`);const a=panel.querySelector('.target-arena');const spawn=()=>{if(a.querySelectorAll('.target').length>=4)return;const t=document.createElement('button');t.className='target';t.style.left=`${rand(Math.max(1,a.clientWidth-52))}px`;t.style.top='-52px';t.onclick=()=>{hits++;sound('success');t.remove();panel.querySelector('#rain-score').textContent=`HITS ${hits}`;spawn()};a.append(t)};for(let i=0;i<3;i++)spawn();every(()=>{a.querySelectorAll('.target').forEach(t=>{const y=parseFloat(t.style.top||'-52')+4;t.style.top=`${y}px`;if(y>a.clientHeight)t.remove()})},35);every(spawn,620);every(()=>{const left=Math.max(0,(end-performance.now())/1000),el=panel.querySelector('#rain-left');if(el)el.textContent=`${left.toFixed(1)}s`;if(left<=0)finishOnce(hits*100,{targets:hits,perfect:hits>=10})},50);return true;
 }
 if(mode==='avoidRed'){
   let round=0,score=0;const next=()=>{if(round>=12)return finishOnce(score*90,{correct:score,rounds:12,perfect:score===12});round++;const red=rand(6);html(`<div class="game-hud"><span>TARGET ${round} / 12</span><span>${score} BLUE HITS</span></div><div class="prompt-label">BLUE SCORES · RED ENDS IT</div><div class="answer-row" style="max-width:430px;margin:24px auto">${Array.from({length:6},(_,i)=>`<button class="target" data-i="${i}" aria-label="${i===red?'Red penalty':'Blue target'}" style="position:relative;inset:auto;margin:13px;background:${i===red?'var(--pink)':'var(--cyan)'}">${i===red?"×":"●"}</button>`).join('')}</div>`);panel.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>{if(Number(b.dataset.i)===red){sound('fail');finishOnce(score*90,{correct:score,rounds:round,perfect:false})}else{score++;sound('success');later(next,90)}})};next();return true;
 }
 return false;
}
