import {rand,pick,shuffle} from './common.js';

const choices=['🍒','🪙','⭐','🍀'];
export function playFun(mode,c){
 const {panel,html,later,every,finishOnce,sound,setCleanup}=c;
 if(!['avoidWrongObject','dontBlink','luckyNumber','higherRoll','impossibleButton','howLucky','beatAI','oneChance'].includes(mode))return false;
 if(mode==='avoidWrongObject'){
   let n=0,score=0;const next=()=>{if(n>=8)return finishOnce(score*125,{correct:score,rounds:8,perfect:score===8});n++;const safe=rand(4);html(`<div class="game-hud"><span>ROUND ${n} / 8</span><span>${score} SAFE PICKS</span></div><div class="prompt-label">TAP THE SAFE OBJECT</div><div class="answer-row">${['🍏','💎','🌟','🎁'].map((x,i)=>`<button class="answer-btn" data-i="${i}" style="font-size:29px;min-width:68px">${x}</button>`).join('')}</div><p class="instructions">Safe object: ${['🍏','💎','🌟','🎁'][safe]}</p>`);panel.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>{if(Number(b.dataset.i)===safe){score++;sound('success');later(next,110)}else{sound('fail');finishOnce(score*125,{correct:score,rounds:n,perfect:false})}})};next();return true;
 }
 if(mode==='dontBlink'){
   html(`<div class="game-hud"><span id="blink-time">5.0s</span><span>STAY INSIDE THE RING</span></div><div class="target-arena" id="blink-arena" style="display:grid;place-items:center;height:300px"><div id="blink-ring" style="width:150px;height:150px;border:4px solid var(--lime);border-radius:50%;box-shadow:0 0 32px #ceff594c;display:grid;place-items:center;font-size:35px;z-index:2">◎</div><div id="blink-decoy" aria-hidden="true" style="position:absolute;left:10%;top:12%;font-size:28px;color:var(--pink);pointer-events:none">✦</div></div><p class="instructions">Stay inside the ring. Ignore the shifting decoy.</p>`);
   const a=panel.querySelector('#blink-arena'),ring=panel.querySelector('#blink-ring'),decoy=panel.querySelector('#blink-decoy'),begin=performance.now(),end=begin+5000,grace=begin+800;let inside=false;
   const check=e=>{const r=ring.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2;inside=Math.hypot(e.clientX-cx,e.clientY-cy)<=r.width/2;if(inside)ring.style.background='var(--lime)';else ring.style.background='transparent';if(performance.now()>grace&&!inside)finishOnce(0,{stayedInside:false})};const leave=()=>{if(performance.now()>grace)finishOnce(0,{stayedInside:false})};
   a.addEventListener('pointermove',check);a.addEventListener('pointerdown',check);a.addEventListener('pointerleave',leave);setCleanup(()=>{a.removeEventListener('pointermove',check);a.removeEventListener('pointerdown',check);a.removeEventListener('pointerleave',leave)});every(()=>{if(decoy){decoy.style.left=`${10+rand(75)}%`;decoy.style.top=`${8+rand(70)}%`}},650);
   every(()=>{const left=Math.max(0,(end-performance.now())/1000),el=panel.querySelector('#blink-time');if(el)el.textContent=`${left.toFixed(1)}s`;if(left<=0)finishOnce(inside?1000:0,{stayedInside:inside,perfect:inside})},40);return true;
 }
 if(mode==='luckyNumber'){
   html(`<div class="prompt-label">PICK YOUR LUCKY NUMBER</div><div class="answer-row">${Array.from({length:10},(_,i)=>`<button class="answer-btn" data-v="${i+1}">${i+1}</button>`).join('')}</div>`);const draw=1+rand(10);panel.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>{const diff=Math.abs(Number(b.dataset.v)-draw),score=Math.max(0,1000-diff*125);sound(score>500?'success':'tap');finishOnce(score,{guess:Number(b.dataset.v),draw,perfect:diff===0})});return true;
 }
 if(mode==='higherRoll'){
   let n=0,streak=0,best=0,current=1+rand(6);const next=()=>{if(n>=6)return finishOnce(best*165,{streak:best,rounds:6,perfect:best===6});n++;let roll=1+rand(6);while(roll===current)roll=1+rand(6);html(`<div class="game-hud"><span>ROLL ${n} / 6</span><span>BEST STREAK ${best}</span></div><div class="prompt-label">NEXT ROLL HIGHER OR LOWER?</div><div class="big-prompt">🎲 ${current}</div><div class="answer-row"><button class="answer-btn" data-v="higher">↑ HIGHER</button><button class="answer-btn" data-v="lower">↓ LOWER</button></div>`);panel.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>{const ok=b.dataset.v===(roll>current?'higher':'lower');if(ok){streak++;best=Math.max(best,streak);sound('success')}else{streak=0;sound('fail')}current=roll;later(next,120)})};next();return true;
 }
 if(mode==='impossibleButton'){
   html(`<div class="game-hud"><span id="impossible-time">6.0s</span></div><div class="prompt-label">CATCH THE RUNAWAY BUTTON</div><div class="target-arena" id="runaway-arena" style="height:300px"><button id="runaway-button" class="button primary" style="position:absolute;left:45%;top:44%">CATCH ME</button></div><p class="instructions">Move toward the button. It will dodge, but you can still catch it.</p>`);const a=panel.querySelector('#runaway-arena'),b=panel.querySelector('#runaway-button'),end=performance.now()+6000;let catches=0;
   const move=e=>{const r=b.getBoundingClientRect(),dx=e.clientX-(r.left+r.width/2),dy=e.clientY-(r.top+r.height/2);if(Math.hypot(dx,dy)<120){const maxX=Math.max(1,a.clientWidth-b.offsetWidth),maxY=Math.max(1,a.clientHeight-b.offsetHeight);b.style.left=`${Math.max(0,Math.min(maxX,(r.left-a.getBoundingClientRect().left)+(dx<0?80:-80)))}px`;b.style.top=`${Math.max(0,Math.min(maxY,(r.top-a.getBoundingClientRect().top)+(dy<0?70:-70)))}px`}};
   a.addEventListener('pointermove',move);setCleanup(()=>a.removeEventListener('pointermove',move));b.onclick=()=>{catches++;sound('success');finishOnce(Math.max(0,1000-Math.round((performance.now()-(end-6000))/6)),{catches,perfect:performance.now()<end-4500})};every(()=>{const left=Math.max(0,(end-performance.now())/1000),el=panel.querySelector('#impossible-time');if(el)el.textContent=`${left.toFixed(1)}s`;if(left<=0)finishOnce(0,{caught:false})},40);return true;
 }
 if(mode==='howLucky'){
   let n=0,score=0;const next=()=>{if(n>=3)return finishOnce(Math.round(score/3),{rounds:3,perfect:score===3000,entertainmentOnly:true});n++;const rounds=[{q:'Which card is red?',options:['♦','♣','♠','♣'],answer:0},{q:'Pick the lucky charm.',options:shuffle(choices),answer:null},{q:'Which side will the coin land on?',options:['HEADS','TAILS'],answer:rand(2)}];const task=rounds[n-1];if(n===2)task.answer=task.options.indexOf(pick(task.options));if(n===1)task.options=['♦','♣','♥','♠'];html(`<div class="game-hud"><span>LUCK TEST ${n} / 3</span><span>${score} LUCK POINTS</span></div><div class="prompt-label">ENTERTAINMENT ONLY · NOT SCIENTIFIC</div><h2>${task.q}</h2><div class="answer-row">${task.options.map((x,i)=>`<button class="answer-btn" data-i="${i}">${x}</button>`).join('')}</div>`);const truth=task.answer;panel.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>{if(Number(b.dataset.i)===truth){score+=1000;sound('success')}else sound('fail');later(next,100)})};next();return true;
 }
 if(mode==='beatAI'){
   let n=0,score=0,wins=0;const moves=['rock','paper','scissors'],beats={rock:'scissors',paper:'rock',scissors:'paper'};const next=()=>{if(n>=5)return finishOnce(score,{wins,rounds:5,simulatedOpponent:true,perfect:wins===5});n++;const ai=pick(moves);html(`<div class="game-hud"><span>DUEL ${n} / 5</span><span>${wins} WINS</span></div><div class="prompt-label">SIMULATED OPPONENT · NOT MACHINE LEARNING</div><div class="answer-row">${moves.map(x=>`<button class="answer-btn" data-v="${x}">${({rock:'🪨',paper:'📄',scissors:'✂️'})[x]}<small style="display:block">${x.toUpperCase()}</small></button>`).join('')}</div>`);panel.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>{const you=b.dataset.v;if(you===ai){score+=50;sound('tap')}else if(beats[you]===ai){score+=200;wins++;sound('success')}else sound('fail');later(next,120)})};next();return true;
 }
 if(mode==='oneChance'){
   const task=pick([
    ()=>{const n=1+rand(40),yes=n%2===0;return{prompt:`One chance: is ${n} even?`,options:['YES','NO'],correct:yes?0:1}},
    ()=>{const a=1+rand(8),b=1+rand(8),ans=a+b,options=shuffle([ans,ans+1,Math.max(0,ans-1),ans+3]);return{prompt:`One chance: ${a} + ${b} = ?`,options,correct:options.indexOf(ans)}},
    ()=>{const x=pick(['▲','●','◆','■']),options=shuffle([x,...['▲','●','◆','■'].filter(v=>v!==x).slice(0,3)]);return{prompt:`One chance: choose ${x}.`,options,correct:options.indexOf(x)}},
    ()=>{const a=rand(30);let b=rand(30);while(b===a)b=rand(30);const options=shuffle([a,b]);return{prompt:`One chance: choose the higher number.`,options,correct:options.indexOf(Math.max(a,b))}}
   ])();html(`<div class="prompt-label">ONE CHANCE · ONE ANSWER</div><h2 style="max-width:560px">${task.prompt}</h2><div class="answer-row">${task.options.map((x,i)=>`<button class="answer-btn" data-i="${i}">${x}</button>`).join('')}</div>`);panel.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>{const ok=Number(b.dataset.i)===task.correct;sound(ok?'success':'fail');finishOnce(ok?1000:0,{correct:ok?1:0,perfect:ok,oneAttempt:true})});return true;
 }
 return false;
}
