import {rand,pick,shuffle,symbols} from './common.js';

const icons=['🐸','🍋','🚀','🦊','🎈','🍄','🐙','🌙','🧸','🍓'];
export function playMemory(mode,c){
 const {panel,html,later,finishOnce,sound}=c;
 if(!['flashNumbers','iconSequence','cardPeek','positionMemory','reverseMemory','memoryPair','vanishingGrid','whatChanged','lastOneStanding'].includes(mode))return false;
 if(mode==='flashNumbers'){
   let level=0;const next=()=>{if(level>=5)return finishOnce(level*200,{correct:level,rounds:5,perfect:true});level++;const length=level+2,num=Array.from({length},()=>rand(10)).join('');html(`<div class="game-hud"><span>LEVEL ${level} / 5</span><span>${length} DIGITS</span></div><div class="prompt-label">MEMORIZE THIS NUMBER</div><div class="big-prompt">${num}</div>`);later(()=>{html(`<div class="prompt-label">TYPE IT BACK</div><input class="game-input" id="flash-num" inputmode="numeric" autocomplete="off" maxlength="12"><button class="button primary" id="flash-check" style="margin-top:12px">CHECK</button>`);const input=panel.querySelector('#flash-num');input.focus();const check=()=>{if(input.value!==num){finishOnce((level-1)*200,{correct:level-1,level,perfect:false});return}sound('success');later(next,180)};panel.querySelector('#flash-check').onclick=check;input.onkeydown=e=>{if(e.key==='Enter')check()}},Math.max(1200,length*430))};next();return true;
 }
 if(mode==='iconSequence'){
   const seq=Array.from({length:5},()=>rand(4));let flash=0,step=0;html(`<div class="prompt-label">WATCH THE ICONS</div><div class="answer-row" id="icon-flashes">${icons.slice(0,4).map((x,i)=>`<div data-icon="${i}" style="width:58px;height:58px;border-radius:16px;background:var(--panel-2);display:grid;place-items:center;font-size:29px">${x}</div>`).join('')}</div><p class="instructions">Repeat the lights in order.</p>`);const show=()=>{if(flash>=seq.length)return later(input,350);const item=panel.querySelector(`[data-icon="${seq[flash]}"]`);item.style.background='var(--lime)';item.style.color='#15190e';later(()=>{item.style.background='';item.style.color='';flash++;later(show,170)},330)};const input=()=>{html(`<div class="game-hud"><span>STEP <b id="icon-step">1 / ${seq.length}</b></span></div><div class="prompt-label">REPEAT THE SEQUENCE</div><div class="answer-row">${icons.slice(0,4).map((x,i)=>`<button class="answer-btn" data-i="${i}" style="font-size:30px">${x}</button>`).join('')}</div>`);panel.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>{if(Number(b.dataset.i)!==seq[step]){finishOnce(step*180,{correct:step,sequenceLength:seq.length});return}step++;sound('tap');if(step===seq.length)finishOnce(1000,{correct:step,perfect:true});else panel.querySelector('#icon-step').textContent=`${step+1} / ${seq.length}`})};later(show,300);return true;
 }
 if(mode==='cardPeek'){
   const cards=shuffle(icons.slice(0,4)),question=pick(cards),answer=cards.indexOf(question);html(`<div class="prompt-label">MEMORIZE THE CARDS</div><div class="answer-row">${cards.map((x,i)=>`<div class="answer-btn" style="font-size:31px">${x}</div>`).join('')}</div><p class="instructions">Where is ${question}?</p>`);later(()=>{html(`<div class="prompt-label">FIND ${question}</div><div class="answer-row">${cards.map((_,i)=>`<button class="answer-btn" data-i="${i}" aria-label="Card ${i+1}">▧</button>`).join('')}</div>`);panel.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>{const ok=Number(b.dataset.i)===answer;sound(ok?'success':'fail');finishOnce(ok?1000:0,{correct:ok?1:0,perfect:ok})})},1500);return true;
 }
 if(mode==='positionMemory'){
   const positions=Array.from({length:5},()=>rand(16));let i=0;html(`<div class="prompt-label">FOLLOW THE MARKER</div><div class="sequence-grid" id="position-grid" style="grid-template-columns:repeat(4,minmax(0,1fr));width:min(340px,100%)">${Array.from({length:16},(_,x)=>`<div class="sequence-cell" data-p="${x}"></div>`).join('')}</div><p class="instructions">Remember where it stops.</p>`);const show=()=>{if(i>=positions.length)return later(input,300);const el=panel.querySelector(`[data-p="${positions[i]}"]`);el.textContent='●';el.classList.add('lit');later(()=>{el.textContent='';el.classList.remove('lit');i++;later(show,120)},310)};const input=()=>{const correct=positions.at(-1),set=new Set([correct]);while(set.size<4)set.add(rand(16));const opts=shuffle([...set]);html(`<div class="prompt-label">WHERE DID IT STOP?</div><div class="answer-row">${opts.map(x=>`<button class="answer-btn" data-v="${x}">${x+1}</button>`).join('')}</div>`);panel.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>{const ok=Number(b.dataset.v)===correct;sound(ok?'success':'fail');finishOnce(ok?1000:0,{correct:ok?1:0,perfect:ok})})};later(show,250);return true;
 }
 if(mode==='reverseMemory'){
   const length=5,num=Array.from({length},()=>rand(10)).join(''),answer=[...num].reverse().join('');html(`<div class="prompt-label">MEMORIZE THE SEQUENCE</div><div class="big-prompt">${num}</div><p class="instructions">Now enter it backwards.</p>`);later(()=>{html(`<div class="prompt-label">TYPE IT IN REVERSE</div><input class="game-input" id="reverse-input" inputmode="numeric" autocomplete="off" maxlength="12"><button class="button primary" id="reverse-submit" style="margin-top:12px">CHECK</button>`);const input=panel.querySelector('#reverse-input');input.focus();const check=()=>{const ok=input.value===answer;sound(ok?'success':'fail');finishOnce(ok?1000:0,{correct:ok?1:0,perfect:ok})};panel.querySelector('#reverse-submit').onclick=check;input.onkeydown=e=>{if(e.key==='Enter')check()}},1900);return true;
 }
 if(mode==='memoryPair'){
   const pair=shuffle([pick(icons),pick(icons)]);while(pair[0]===pair[1])pair[1]=pick(icons);const deck=shuffle([...pair,...pair]);let first=null,matches=0,locked=false,turns=0;const render=()=>{html(`<div class="game-hud"><span>PAIRS ${matches} / 2</span><span>FLIPS ${turns}</span></div><div class="prompt-label">FIND BOTH MATCHING PAIRS</div><div class="sequence-grid" style="grid-template-columns:repeat(2,minmax(0,1fr));width:min(245px,100%)">${deck.map((x,i)=>`<button class="sequence-cell" data-i="${i}">${x==='?'?'▧':x}</button>`).join('')}</div>`);panel.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>{if(locked||b.textContent==='▧')return;turns++;if(first===null){first=Number(b.dataset.i);b.classList.add('lit');return}const second=Number(b.dataset.i);locked=true;panel.querySelector(`[data-i="${first}"]`).classList.add('lit');b.classList.add('lit');if(deck[first]===deck[second]){matches++;sound('success');deck[first]='?';deck[second]='?';if(matches===2){finishOnce(Math.max(300,1200-turns*80),{pairs:2,flips:turns,perfect:turns===2});return}later(()=>{first=null;locked=false;render()},300)}else{sound('fail');later(()=>{first=null;locked=false;render()},550)}})};render();return true;
 }
 if(mode==='vanishingGrid'){
   let level=0,total=0;const startLevel=()=>{if(level>=4)return finishOnce(total*250,{correct:level,rounds:4,perfect:level===4});level++;const size=4,count=level+2,set=new Set();while(set.size<count)set.add(rand(size*size));html(`<div class="game-hud"><span>LEVEL ${level} / 4</span><span>${count} TILES</span></div><div class="prompt-label">MEMORIZE ALL LIT CELLS</div><div class="tile-grid" style="grid-template-columns:repeat(${size},minmax(0,1fr));width:min(340px,100%)">${Array.from({length:size*size},(_,i)=>`<div class="tile ${set.has(i)?'on':''}"></div>`).join('')}</div>`);later(()=>{html(`<div class="prompt-label">REBUILD LEVEL ${level}</div><div class="tile-grid" style="grid-template-columns:repeat(${size},minmax(0,1fr));width:min(340px,100%)">${Array.from({length:size*size},(_,i)=>`<button class="tile" data-i="${i}"></button>`).join('')}</div><button class="button primary" id="grid-submit">CHECK</button>`);const picked=new Set();panel.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>{const id=Number(b.dataset.i);if(picked.has(id)){picked.delete(id);b.classList.remove('on')}else{picked.add(id);b.classList.add('on')}});panel.querySelector('#grid-submit').onclick=()=>{const ok=picked.size===set.size&&[...set].every(x=>picked.has(x));if(ok){total++;sound('success');later(startLevel,180)}else{sound('fail');finishOnce(total*250,{correct:total,level,perfect:false})}}},1100+level*120)};startLevel();return true;
 }
 if(mode==='whatChanged'){
   let round=0,score=0;const next=()=>{if(round>=6)return finishOnce(score*165,{correct:score,rounds:6,perfect:score===6});round++;const before=Array.from({length:5},()=>pick(icons)),idx=rand(5),after=[...before];after[idx]=pick(icons.filter(x=>x!==before[idx]));html(`<div class="game-hud"><span>SCENE ${round} / 6</span></div><div class="prompt-label">REMEMBER THIS SCENE</div><div class="answer-row" style="font-size:31px">${before.map(x=>`<span>${x}</span>`).join('')}</div>`);later(()=>{html(`<div class="prompt-label">WHAT CHANGED?</div><div class="answer-row" style="font-size:31px">${after.map((x,i)=>`<button class="answer-btn" data-i="${i}">${x}</button>`).join('')}</div>`);panel.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>{if(Number(b.dataset.i)===idx){score++;sound('success')}else sound('fail');later(next,100)})},900)};next();return true;
 }
 if(mode==='lastOneStanding'){
   const remain=rand(6),cast=shuffle(icons.slice(0,6));html(`<div class="prompt-label">WATCH THE ELIMINATION</div><div class="answer-row" id="survivors" style="font-size:31px">${cast.map((x,i)=>`<span data-i="${i}">${x}</span>`).join('')}</div><p class="instructions">Track the object that is left at the end.</p>`);let step=0;const eliminate=()=>{if(step>=cast.length-1)return later(input,500);let victim=step===remain?step+1:step;if(victim>=cast.length)victim=step;const el=panel.querySelector(`[data-i="${victim}"]`);if(el)el.style.opacity='0.12';step++;later(eliminate,360)};const input=()=>{html(`<div class="prompt-label">WHICH ONE REMAINED?</div><div class="answer-row">${cast.map((x,i)=>`<button class="answer-btn" data-i="${i}" style="font-size:28px">${x}</button>`).join('')}</div>`);panel.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>{const ok=Number(b.dataset.i)===remain;sound(ok?'success':'fail');finishOnce(ok?1000:0,{correct:ok?1:0,perfect:ok})})};later(eliminate,500);return true;
 }
 return false;
}
