import {rand,pick,shuffle,symbols} from './common.js';

const drawGrid=(n,content,cellStyle='')=>`<div class="sequence-grid" style="grid-template-columns:repeat(${n},minmax(0,1fr));width:min(350px,100%)">${content.map((x,i)=>`<button class="sequence-cell" data-cell="${i}" style="${cellStyle}">${x}</button>`).join('')}</div>`;

export function playVision(mode,c){
 const {panel,html,later,finishOnce,sound}=c;
 if(!['findDot','whichShape','colorIntruder','missingTile','mirrorImage','flashMemory','sameDifferent','hiddenNumber','pixelHunt','visualCountRush'].includes(mode))return false;
 if(mode==='findDot'||mode==='pixelHunt'){
   const size=mode==='findDot'?5:6,total=size*size,odd=rand(total),delta=mode==='findDot'?2:11;
   html(`<div class="prompt-label">${mode==='findDot'?'FIND THE DIFFERENT DOT':'FIND THE CHANGED PIXEL'}</div><div class="game-hud"><span>ONE IS DIFFERENT</span></div><div class="sequence-grid" style="grid-template-columns:repeat(${size},minmax(0,1fr));width:min(370px,100%);gap:7px">${Array.from({length:total},(_,i)=>`<button class="sequence-cell" data-cell="${i}" aria-label="Tile ${i+1}" style="height:auto;aspect-ratio:1;border-radius:50%;background:${mode==='pixelHunt'?`hsl(191 75% ${i===odd?58+delta:58}%)`:'var(--cyan)'};transform:${mode==='findDot'&&i===odd?'scale(1.27)':''}"></button>`).join('')}</div>`);
   panel.querySelectorAll('[data-cell]').forEach(b=>b.onclick=()=>{const ok=Number(b.dataset.cell)===odd;sound(ok?'success':'fail');finishOnce(ok?1000:0,{correct:ok?1:0,perfect:ok})});return true;
 }
 if(mode==='whichShape'){
   let round=0,score=0;const shapeSet=['●','▲','◆','■','⬟','✦'];const next=()=>{if(round>=8)return finishOnce(score*125,{correct:score,rounds:8,perfect:score===8});round++;const target=pick(shapeSet),set=new Set([target]);while(set.size<4)set.add(pick(shapeSet.filter(x=>!set.has(x))));const choices=shuffle([...set]);html(`<div class="game-hud"><span>SHAPE ${round} / 8</span><span>${score} MATCHED</span></div><div class="prompt-label">WHICH ONE MATCHES?</div><div class="big-prompt">${target}</div><div class="answer-row">${choices.map(s=>`<button class="answer-btn" data-v="${s}" style="font-size:32px;min-width:70px">${s}</button>`).join('')}</div>`);panel.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>{if(b.dataset.v===target){score++;sound('success')}else sound('fail');later(next,100)})};next();return true;
 }
 if(mode==='colorIntruder'){
   let round=0,score=0;const next=()=>{if(round>=7)return finishOnce(score*140,{correct:score,rounds:7,perfect:score===7});round++;const odd=rand(16),hue=rand(360),delta=Math.max(9,24-round*2);html(`<div class="game-hud"><span>ROUND ${round} / 7</span><span>${score} FOUND</span></div><div class="prompt-label">SPOT THE SLIGHTLY DIFFERENT HUE</div><div class="sequence-grid" style="grid-template-columns:repeat(4,minmax(0,1fr));width:min(350px,100%)">${Array.from({length:16},(_,i)=>`<button class="sequence-cell" data-cell="${i}" aria-label="Color tile ${i+1}" style="aspect-ratio:1;background:hsl(${(hue+(i===odd?delta:0))} 72% 59%);border:0"></button>`).join('')}</div>`);panel.querySelectorAll('[data-cell]').forEach(b=>b.onclick=()=>{if(Number(b.dataset.cell)===odd){score++;sound('success')}else sound('fail');later(next,130)})};next();return true;
 }
 if(mode==='missingTile'){
   let round=0,score=0;const next=()=>{if(round>=5)return finishOnce(score*200,{correct:score,rounds:5,perfect:score===5});round++;const count=9+rand(4),odd=rand(count),icons=Array.from({length:count},()=>pick(symbols)),missing=icons[odd];html(`<div class="game-hud"><span>GRID ${round} / 5</span></div><div class="prompt-label">REMEMBER THE TILE POSITIONS</div><div class="sequence-grid" style="grid-template-columns:repeat(4,minmax(0,1fr));width:min(350px,100%)">${Array.from({length:count},(_,i)=>`<div class="sequence-cell">${icons[i]}</div>`).join('')}</div>`);later(()=>{html(`<div class="prompt-label">WHERE WAS ${missing}?</div><div class="sequence-grid" style="grid-template-columns:repeat(4,minmax(0,1fr));width:min(350px,100%)">${Array.from({length:count},(_,i)=>`<button class="sequence-cell" data-cell="${i}" aria-label="Grid cell ${i+1}">?</button>`).join('')}</div>`);panel.querySelectorAll('[data-cell]').forEach(b=>b.onclick=()=>{if(Number(b.dataset.cell)===odd){score++;sound('success')}else sound('fail');later(next,140)})},1150)};next();return true;
 }
 if(mode==='mirrorImage'){
   let round=0,score=0;const next=()=>{if(round>=6)return finishOnce(score*165,{correct:score,rounds:6,perfect:score===6});round++;const bad=rand(4),pairs=Array.from({length:4},()=>['←','→']);pairs[bad]=['←','←'];html(`<div class="game-hud"><span>PAIR ${round} / 6</span></div><div class="prompt-label">FIND THE PAIR THAT ISN’T MIRRORED</div><div class="answer-row">${pairs.map((p,i)=>`<button class="answer-btn" data-i="${i}" style="font-size:31px;min-width:92px">${p[0]}　${p[1]}</button>`).join('')}</div>`);panel.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>{if(Number(b.dataset.i)===bad){score++;sound('success')}else sound('fail');later(next,120)})};next();return true;
 }
 if(mode==='flashMemory'){
   const size=4,total=16,cell=rand(total);html(`<div class="prompt-label">WATCH THE FLASH</div><div class="sequence-grid" style="grid-template-columns:repeat(4,minmax(0,1fr));width:min(340px,100%)">${Array.from({length:total},(_,i)=>`<div class="sequence-cell ${i===cell?'lit':''}"></div>`).join('')}</div><p class="instructions">Tap the cell that flashed.</p>`);later(()=>{html(`<div class="prompt-label">WHERE DID IT FLASH?</div>${drawGrid(4,Array(total).fill(''))}`);panel.querySelectorAll('[data-cell]').forEach(b=>b.onclick=()=>{const ok=Number(b.dataset.cell)===cell;sound(ok?'success':'fail');finishOnce(ok?1000:0,{correct:ok?1:0,perfect:ok})})},700);return true;
 }
 if(mode==='sameDifferent'){
   let round=0,score=0;const next=()=>{if(round>=8)return finishOnce(score*125,{correct:score,rounds:8,perfect:score===8});round++;const same=Math.random()<.5,left=Array.from({length:5},()=>pick(symbols)),right=same?[...left]:[...left];if(!same){let i=rand(5);right[i]=pick(symbols.filter(x=>x!==right[i]))}html(`<div class="game-hud"><span>COMPARE ${round} / 8</span></div><div class="prompt-label">SAME OR DIFFERENT?</div><div style="display:flex;gap:22px;align-items:center;font-size:38px;margin:18px 0"><div>${left.join(' ')}</div><span>?</span><div>${right.join(' ')}</div></div><div class="answer-row"><button class="answer-btn" data-v="same">SAME</button><button class="answer-btn" data-v="different">DIFFERENT</button></div>`);panel.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>{if(b.dataset.v===(same?'same':'different')){score++;sound('success')}else sound('fail');later(next,130)})};next();return true;
 }
 if(mode==='hiddenNumber'){
   let round=0,score=0;const next=()=>{if(round>=6)return finishOnce(score*165,{correct:score,rounds:6,perfect:score===6});round++;const odd=rand(16),d=String(rand(10));html(`<div class="game-hud"><span>HUNT ${round} / 6</span></div><div class="prompt-label">FIND THE ONLY NUMBER</div><div class="sequence-grid" style="grid-template-columns:repeat(4,minmax(0,1fr));width:min(340px,100%)">${Array.from({length:16},(_,i)=>`<button class="sequence-cell" data-cell="${i}">${i===odd?d:pick(['O','I','S','B','Z','G'])}</button>`).join('')}</div>`);panel.querySelectorAll('[data-cell]').forEach(b=>b.onclick=()=>{if(Number(b.dataset.cell)===odd){score++;sound('success')}else sound('fail');later(next,100)})};next();return true;
 }
 if(mode==='visualCountRush'){
   let round=0,score=0;const next=()=>{if(round>=6)return finishOnce(score*165,{correct:score,rounds:6,perfect:score===6});round++;const target=pick(['●','◆','▲']),count=2+rand(9),noise=Array.from({length:count+rand(6)},()=>pick(['●','◆','▲'].filter(x=>x!==target)));for(let i=0;i<count;i++)noise.splice(rand(noise.length+1),0,target);html(`<div class="game-hud"><span>FLASH ${round} / 6</span><span>${score} RIGHT</span></div><div class="prompt-label">COUNT THE ${target} SYMBOLS</div><div style="display:flex;flex-wrap:wrap;justify-content:center;gap:12px;font-size:29px;min-height:115px;max-width:430px">${shuffle(noise).map(s=>`<span>${s}</span>`).join('')}</div>`);later(()=>{html(`<div class="prompt-label">HOW MANY ${target} SYMBOLS?</div><div class="answer-row">${[count,Math.max(1,count-1),count+1,count+2].filter((x,i,a)=>a.indexOf(x)===i).sort(()=>Math.random()-.5).map(x=>`<button class="answer-btn" data-v="${x}">${x}</button>`).join('')}</div>`);panel.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>{if(Number(b.dataset.v)===count){score++;sound('success')}else sound('fail');later(next,100)})},800)};next();return true;
 }
 return false;
}
