import { isExtraArcadeMode, mountExtraArcade } from './arcade-extra.js';
import { startCountdown } from '../lib/countdown.js';
import { isReverseDirection, swipeDirection, supportsTouchInput } from '../lib/touch.js';
import { mountEdgeSurf } from './edge-surf.js';

const pieces=[[[1,1,1,1]],[[1,1],[1,1]],[[0,1,0],[1,1,1]],[[1,0,0],[1,1,1]],[[0,0,1],[1,1,1]],[[1,1,0],[0,1,1]],[[0,1,1],[1,1,0]]];
const colors=['#5fe5ff','#7ee7e4','#a696ff','#ff7b9b','#77a8ff','#ffbd67','#d288ff'];
const clone=m=>m.map(r=>r.slice());
export function mountArcade({panel,game,finish,sound,onStart=()=>{},startLevel=0}){
 if(game.mode==='edgeSurf')return mountEdgeSurf({panel,game,finish,sound,onStart,startLevel});
 if(isExtraArcadeMode(game.mode))return mountExtraArcade({panel,game,finish,sound,onStart});
 let dead=false,done=false,raf=0,timer=0,handler=null,score=0,last=0,spawn=0,countdownCancel=null;
 const cleanup=()=>{dead=true;countdownCancel?.();cancelAnimationFrame(raf);clearInterval(timer);if(handler)window.removeEventListener('keydown',handler)};
 const end=(n=score,extra={})=>{if(done||dead)return;done=true;cleanup();finish({score:Math.max(0,Math.round(n)),elapsed:performance.now()-last,perfect:false,...extra})};
 const drawStart=()=>{panel.innerHTML=`<div class="eyebrow">ARCADE · ${game.difficulty}</div><h2>${game.title}</h2><p class="instructions">${game.instructions}</p><button class="button primary" id="arcade-start">PLAY NOW →</button><p class="mono muted" style="margin-top:20px">ARCADE / QUICK PLAY</p>`;panel.querySelector('#arcade-start').onclick=run};
 function run(){if(dead||last||countdownCancel)return;sound('click');countdownCancel=startCountdown({panel,sound,onStart:()=>onStart(game.category),onGo:()=>{countdownCancel=null;last=performance.now();if(game.mode==='snake')snake();else if(game.mode==='blocks')blocks();else runner()}})}
 function mountCanvas(width,height){panel.classList.add('playing');panel.innerHTML=`<div class="game-hud"><span id="arc-score">SCORE 0</span><span id="arc-info">${game.mode==='blocks'?'LINES 0':'STAY ALIVE'}</span></div><canvas class="canvas-game" width="${width}" height="${height}" style="width:min(${width}px,100%);height:auto" aria-label="${game.title} playfield"></canvas><div class="touch-controls" id="touch-controls"></div>`;return panel.querySelector('canvas')}
 function updateScore(){const el=panel.querySelector('#arc-score');if(el)el.textContent=`SCORE ${Math.floor(score)}`}
 const touchDevice=()=>supportsTouchInput({maxTouchPoints:navigator.maxTouchPoints,coarsePointer:window.matchMedia('(pointer: coarse)').matches});
 function controls(items){if(!touchDevice())return;const box=panel.querySelector('#touch-controls');if(!box)return;box.classList.add('touch-controls-mobile');items.forEach(([text,fn])=>{const b=document.createElement('button');b.type='button';b.textContent=text;b.setAttribute('aria-label',text);b.onclick=fn;box.append(b)})}
 function snake(){const c=mountCanvas(520,400),ctx=c.getContext('2d'),W=520,H=400;let path=[],length=105,dir={x:1,y:0},turns=[],fruit={x:350,y:170},lastFrame=0,stepDistance=0;
  let head={x:220,y:200};for(let i=0;i<26;i++)path.push({x:head.x-i*4,y:head.y});
  const turn=d=>{const last=turns.at(-1)||dir;if(isReverseDirection(last,d))return;if(last.x!==d.x||last.y!==d.y)turns.push(d)};
  const placeFruit=()=>{for(let tries=0;tries<150;tries++){const p={x:24+Math.random()*(W-48),y:24+Math.random()*(H-48)};if(path.every((v,i)=>i%3||Math.hypot(v.x-p.x,v.y-p.y)>38)){fruit=p;return}}fruit={x:80+Math.random()*350,y:60+Math.random()*260}};
  let swipeStart=null;c.style.touchAction='none';c.addEventListener('pointerdown',event=>{if(event.pointerType==='mouse')return;swipeStart={x:event.clientX,y:event.clientY};event.preventDefault()},{passive:false});c.addEventListener('pointerup',event=>{if(!swipeStart||event.pointerType==='mouse')return;const d=swipeDirection(event.clientX-swipeStart.x,event.clientY-swipeStart.y);swipeStart=null;if(d)turn(d)});c.addEventListener('pointercancel',()=>swipeStart=null);
  handler=e=>{const k=e.key.toLowerCase();if(['arrowup','w'].includes(k))turn({x:0,y:-1});else if(['arrowdown','s'].includes(k))turn({x:0,y:1});else if(['arrowleft','a'].includes(k))turn({x:-1,y:0});else if(['arrowright','d'].includes(k))turn({x:1,y:0});else return;e.preventDefault()};window.addEventListener('keydown',handler);
  controls([['↑',()=>turn({x:0,y:-1})],['←',()=>turn({x:-1,y:0})],['↓',()=>turn({x:0,y:1})],['→',()=>turn({x:1,y:0})]]);
  const sampleTrail=()=>{const points=[path[0]];let accumulated=0;for(let i=1;i<path.length;i++){const a=path[i-1],b=path[i],segment=Math.hypot(a.x-b.x,a.y-b.y);accumulated+=segment;points.push(b);if(accumulated>=length)break}return points};
  const paint=()=>{ctx.fillStyle='#10232a';ctx.fillRect(0,0,W,H);ctx.fillStyle='#16343b';ctx.beginPath();ctx.roundRect(12,12,W-24,H-24,24);ctx.fill();ctx.strokeStyle='#ffffff12';ctx.lineWidth=2;for(let i=0;i<8;i++){ctx.beginPath();ctx.moveTo(26,45+i*44);ctx.quadraticCurveTo(W/2,35+i*44,W-26,45+i*44);ctx.stroke()}
   ctx.fillStyle='#ffbd67';ctx.beginPath();ctx.arc(fruit.x,fruit.y,10,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff0c2';ctx.beginPath();ctx.arc(fruit.x-3,fruit.y-3,3,0,Math.PI*2);ctx.fill();
   const trail=sampleTrail();ctx.lineCap='round';ctx.lineJoin='round';ctx.strokeStyle='#87bd50';ctx.lineWidth=22;ctx.beginPath();trail.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke();ctx.strokeStyle='#b5e56d';ctx.lineWidth=13;ctx.stroke();ctx.fillStyle='#e7ff9a';ctx.beginPath();ctx.arc(head.x,head.y,11,0,Math.PI*2);ctx.fill();const eyeX=head.x+dir.x*5-dir.y*4,eyeY=head.y+dir.y*5+dir.x*4;ctx.fillStyle='#10232a';ctx.beginPath();ctx.arc(eyeX,eyeY,2.5,0,Math.PI*2);ctx.fill()};
  const loop=now=>{if(dead)return;raf=requestAnimationFrame(loop);const dt=Math.min(.035,(now-(lastFrame||now))/1000);lastFrame=now;if(dt<=0){paint();return}const speed=128+Math.min(90,score*.45),travel=speed*dt;stepDistance+=travel;let remaining=travel,turnsUsed=0;while(remaining>0){const stride=Math.min(remaining,4);remaining-=stride;head={x:head.x+dir.x*stride,y:head.y+dir.y*stride};path.unshift(head);let kept=0;for(let i=1;i<path.length;i++){kept+=Math.hypot(path[i-1].x-path[i].x,path[i-1].y-path[i].y);if(kept>=length+8){path.length=i+1;break}}if(Math.hypot(head.x-fruit.x,head.y-fruit.y)<19){score+=10;length+=20;sound('eat');placeFruit();updateScore()}
    if(turns.length&&stepDistance>=23){const next=turns.shift();if(!isReverseDirection(dir,next))dir=next;stepDistance=0;turnsUsed++}if(turnsUsed>3)turns.length=0;
    if(head.x<24||head.y<24||head.x>W-24||head.y>H-24){end(score,{fruit:score/10});return}
    const trail=sampleTrail();for(let i=7;i<trail.length-2;i+=3){if(Math.hypot(head.x-trail[i].x,head.y-trail[i].y)<14){end(score,{fruit:score/10});return}}
   }paint()};paint();raf=requestAnimationFrame(loop)
 }
 function runner(){const c=mountCanvas(520,310),ctx=c.getContext('2d');let y=0,vy=0,onGround=true,obstacles=[],frame=0,speed=3,season=-1;const jump=()=>{if(onGround){vy=-10.5;onGround=false;sound('tap')}};c.onclick=jump;handler=e=>{if([' ','arrowup','w'].includes(e.key.toLowerCase())){e.preventDefault();jump()}};window.addEventListener('keydown',handler);controls([['JUMP',jump]]);
  const biomes=[{name:'CLOVER FIELDS',sky:'#8bd9e8',far:'#6bb29a',near:'#397d67',ground:'#688f43',prop:'tree'},{name:'RED ROCK PASS',sky:'#f1ad72',far:'#ba765c',near:'#834e58',ground:'#715147',prop:'cactus'},{name:'MOONLIT COAST',sky:'#344a78',far:'#546a89',near:'#293f60',ground:'#344b62',prop:'palm'},{name:'FROSTLINE',sky:'#b7d9e8',far:'#91b5c8',near:'#57758e',ground:'#b3c6ca',prop:'pine'},{name:'NEON DISTRICT',sky:'#37304f',far:'#6d527f',near:'#354e70',ground:'#39465b',prop:'tower'}];
  const landscape=(theme,now)=>{ctx.fillStyle=theme.sky;ctx.fillRect(0,0,520,260);ctx.fillStyle=theme.far;ctx.beginPath();ctx.moveTo(0,170);for(let x=0;x<=520;x+=52)ctx.lineTo(x,125+Math.sin(x*.016+score*.004)*28);ctx.lineTo(520,260);ctx.lineTo(0,260);ctx.fill();ctx.fillStyle=theme.near;ctx.beginPath();ctx.moveTo(0,215);for(let x=0;x<=520;x+=40)ctx.lineTo(x,172+Math.sin(x*.023+score*.009)*22);ctx.lineTo(520,260);ctx.lineTo(0,260);ctx.fill();
    for(let i=0;i<8;i++){const x=((i*91-score*(i%2?1.2:.45))%650+650)%650-70,y=210+(i%3)*13;ctx.fillStyle=theme.near;if(theme.prop==='tree'){ctx.fillRect(x+14,y-25,8,28);ctx.beginPath();ctx.arc(x+18,y-27,18,0,Math.PI*2);ctx.fill()}else if(theme.prop==='cactus'){ctx.fillRect(x+13,y-37,9,40);ctx.fillRect(x+2,y-26,13,7);ctx.fillRect(x+2,y-32,7,12);ctx.fillRect(x+19,y-20,12,7);ctx.fillRect(x+25,y-28,7,15)}else if(theme.prop==='palm'){ctx.fillRect(x+15,y-29,6,30);for(let a=0;a<5;a++){ctx.fillRect(x+2+a*7,y-33-(a%2)*4,21,5)}}else if(theme.prop==='pine'){for(let j=0;j<3;j++){ctx.beginPath();ctx.moveTo(x+18,y-43+j*11);ctx.lineTo(x+2,y-8+j*8);ctx.lineTo(x+34,y-8+j*8);ctx.fill()}}else{ctx.fillRect(x,y-30,30,31);ctx.fillStyle='#ffe58d';for(let j=0;j<3;j++)ctx.fillRect(x+5+j*9,y-23,4,5)}}
    ctx.fillStyle=theme.ground;ctx.fillRect(0,260,520,50);ctx.fillStyle='#ffffff28';for(let i=0;i<12;i++){const x=((i*61-score*4)%580+580)%580-30;ctx.fillRect(x,270+(i%3)*9,23,3)}ctx.fillStyle='#ffffff30';ctx.fillRect(0,258,520,3);ctx.fillStyle='#11151b';ctx.font='11px monospace';ctx.fillText(`ZONE ${theme.name}  ·  ${Math.floor(score)} M`,18,24)};
  const drawRunner=(px,py,now)=>{const cycle=onGround?Math.sin(now*.018):0;ctx.fillStyle='#10131d55';ctx.beginPath();ctx.ellipse(px+13,260,17,4,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#243040';ctx.lineWidth=6;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(px+12,py+21);ctx.lineTo(px+7+cycle*5,py+31);ctx.lineTo(px+2+cycle*8,py+32);ctx.moveTo(px+14,py+21);ctx.lineTo(px+19-cycle*5,py+30);ctx.lineTo(px+24-cycle*8,py+31);ctx.stroke();ctx.fillStyle='#f27d58';ctx.beginPath();ctx.roundRect(px+3,py+7,21,20,6);ctx.fill();ctx.fillStyle='#ffd06b';ctx.fillRect(px+6,py+9,15,4);ctx.fillStyle='#efbc91';ctx.beginPath();ctx.arc(px+14,py+5,9,0,Math.PI*2);ctx.fill();ctx.fillStyle='#395371';ctx.beginPath();ctx.arc(px+14,py+3,10,Math.PI,Math.PI*2);ctx.fill();ctx.fillRect(px+5,py+2,18,4);ctx.fillStyle='#16222b';ctx.fillRect(px+17,py+5,2,2);ctx.strokeStyle='#efbc91';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(px+6,py+12);ctx.lineTo(px+1-cycle*4,py+19);ctx.moveTo(px+21,py+12);ctx.lineTo(px+26+cycle*4,py+18);ctx.stroke()};
  const loop=now=>{if(dead)return;raf=requestAnimationFrame(loop);const dt=Math.min(32,now-(frame||now));frame=now;speed+=dt*.0002;const ground=260;y+=vy*(dt/16);if(!onGround)vy+=.55*(dt/16);if(y>=0){y=0;vy=0;onGround=true}spawn+=dt;if(spawn>Math.max(550,1500-speed*100)){obstacles.push({x:550,w:24+Math.random()*20,h:28+Math.random()*34});spawn=0}obstacles.forEach(o=>o.x-=speed*(dt/16));obstacles=obstacles.filter(o=>o.x>-50);score+=dt*.035;const px=75,py=ground-36+y;for(const o of obstacles)if(o.x<px+26&&o.x+o.w>px+5&&py+31>ground-o.h){end(Math.floor(score),{distance:Math.floor(score)});return}
   const band=Math.floor(score/85),theme=biomes[band%biomes.length];if(band!==season){season=band;const el=panel.querySelector('#arc-info');if(el)el.textContent=theme.name}
   landscape(theme,now);drawRunner(px,py,now);obstacles.forEach(o=>{ctx.fillStyle=o.h>50?'#ff7b9b':'#ffbd67';ctx.beginPath();ctx.roundRect(o.x,ground-o.h,o.w,o.h,5);ctx.fill();ctx.fillStyle='#ffffff45';ctx.fillRect(o.x+4,ground-o.h+5,Math.min(7,o.w-8),3)});updateScore()};raf=requestAnimationFrame(loop)
 }
 function blocks(){const c=mountCanvas(300,600),ctx=c.getContext('2d'),W=10,H=20,grid=Array.from({length:H},()=>Array(W).fill(0));let current=nextPiece(),lines=0,fall=0;function nextPiece(){const i=Math.floor(Math.random()*pieces.length);return {m:clone(pieces[i]),x:3,y:0,color:colors[i]}}function collides(m,x,y){for(let r=0;r<m.length;r++)for(let k=0;k<m[r].length;k++)if(m[r][k]&&(x+k<0||x+k>=W||y+r>=H||(y+r>=0&&grid[y+r][x+k])))return true;return false}function lock(){current.m.forEach((r,y)=>r.forEach((v,x)=>{if(v&&current.y+y>=0)grid[current.y+y][current.x+x]=current.color}));let cleared=0;for(let y=H-1;y>=0;y--)if(grid[y].every(Boolean)){grid.splice(y,1);grid.unshift(Array(W).fill(0));cleared++;y++}if(cleared){lines+=cleared;score+=cleared*cleared*100;sound('success');const e=panel.querySelector('#arc-info');if(e)e.textContent=`LINES ${lines}`}current=nextPiece();if(collides(current.m,current.x,current.y)){end(score,{lines});return}updateScore()}
  const move=(dx,dy=0)=>{if(!collides(current.m,current.x+dx,current.y+dy)){current.x+=dx;current.y+=dy;paint();return true}if(dy){lock();paint()}return false};const rotate=()=>{const m=current.m[0].map((_,i)=>current.m.map(r=>r[i]).reverse());if(!collides(m,current.x,current.y))current.m=m;paint()};const hardDrop=()=>{while(!collides(current.m,current.x,current.y+1))current.y++;lock();paint()};handler=e=>{const k=e.key.toLowerCase();if(['arrowleft','a'].includes(k))move(-1);else if(['arrowright','d'].includes(k))move(1);else if(['arrowdown','s'].includes(k))move(0,1);else if(['arrowup','w','x'].includes(k))rotate();else if(e.code==='Space')hardDrop();else return;e.preventDefault()};window.addEventListener('keydown',handler);controls([['←',()=>move(-1)],['↻',rotate],['→',()=>move(1)],['↓',()=>move(0,1)],['DROP',hardDrop]]);
  function paint(){ctx.fillStyle='#10131d';ctx.fillRect(0,0,300,600);ctx.strokeStyle='#ffffff0c';for(let x=0;x<=W;x++){ctx.beginPath();ctx.moveTo(x*30,0);ctx.lineTo(x*30,600);ctx.stroke()}for(let y=0;y<=H;y++){ctx.beginPath();ctx.moveTo(0,y*30);ctx.lineTo(300,y*30);ctx.stroke()}grid.forEach((row,y)=>row.forEach((v,x)=>v&&block(x,y,v)));current.m.forEach((r,y)=>r.forEach((v,x)=>v&&block(current.x+x,current.y+y,current.color)))}function block(x,y,color){if(y<0)return;ctx.fillStyle=color;ctx.beginPath();ctx.roundRect(x*30+2,y*30+2,26,26,5);ctx.fill();ctx.fillStyle='#ffffff2c';ctx.fillRect(x*30+5,y*30+5,18,3)}
  const tick=()=>{if(dead)return;if(!collides(current.m,current.x,current.y+1))current.y++;else lock();paint()};const interval=()=>Math.max(130,650-lines*48);const schedule=()=>{timer=setTimeout(()=>{tick();if(!dead)schedule()},interval())};schedule();paint()
 }
 drawStart();return {start:run,cleanup};
}
