import { isExtraArcadeMode, mountExtraArcade } from './arcade-extra.js';
import { startCountdown } from '../lib/countdown.js';

const pieces=[[[1,1,1,1]],[[1,1],[1,1]],[[0,1,0],[1,1,1]],[[1,0,0],[1,1,1]],[[0,0,1],[1,1,1]],[[1,1,0],[0,1,1]],[[0,1,1],[1,1,0]]];
const colors=['#5fe5ff','#7ee7e4','#a696ff','#ff7b9b','#77a8ff','#ffbd67','#d288ff'];
const clone=m=>m.map(r=>r.slice());
export function mountArcade({panel,game,finish,sound,onStart=()=>{}}){
 if(isExtraArcadeMode(game.mode))return mountExtraArcade({panel,game,finish,sound,onStart});
 let dead=false,done=false,raf=0,timer=0,handler=null,score=0,last=0,spawn=0,countdownCancel=null;
 const cleanup=()=>{dead=true;countdownCancel?.();cancelAnimationFrame(raf);clearInterval(timer);if(handler)window.removeEventListener('keydown',handler)};
 const end=(n=score,extra={})=>{if(done||dead)return;done=true;cleanup();finish({score:Math.max(0,Math.round(n)),elapsed:performance.now()-last,perfect:false,...extra})};
 const drawStart=()=>{panel.innerHTML=`<div class="eyebrow">ARCADE · ${game.difficulty}</div><h2>${game.title}</h2><p class="instructions">${game.instructions}</p><button class="button primary" id="arcade-start">PLAY NOW →</button><p class="mono muted" style="margin-top:20px">ARCADE / QUICK PLAY</p>`;panel.querySelector('#arcade-start').onclick=run};
 function run(){if(dead||last||countdownCancel)return;sound('click');countdownCancel=startCountdown({panel,sound,onStart:()=>onStart(game.category),onGo:()=>{countdownCancel=null;last=performance.now();if(game.mode==='snake')snake();else if(game.mode==='blocks')blocks();else runner()}})}
 function mountCanvas(width,height){panel.classList.add('playing');panel.innerHTML=`<div class="game-hud"><span id="arc-score">SCORE 0</span><span id="arc-info">${game.mode==='blocks'?'LINES 0':'STAY ALIVE'}</span></div><canvas class="canvas-game" width="${width}" height="${height}" style="width:min(${width}px,100%);height:auto" aria-label="${game.title} playfield"></canvas><div class="touch-controls" id="touch-controls"></div>`;return panel.querySelector('canvas')}
 function updateScore(){const el=panel.querySelector('#arc-score');if(el)el.textContent=`SCORE ${Math.floor(score)}`}
 function controls(items){const box=panel.querySelector('#touch-controls');items.forEach(([text,fn])=>{const b=document.createElement('button');b.textContent=text;b.setAttribute('aria-label',text);b.onclick=fn;box.append(b)})}
 function snake(){const c=mountCanvas(400,400),ctx=c.getContext('2d'),cell=20,N=20;let body=[{x:8,y:10},{x:7,y:10},{x:6,y:10}],dir={x:1,y:0},queued={x:1,y:0},fruit;
  const fruitPlace=()=>{const free=[];for(let y=0;y<N;y++)for(let x=0;x<N;x++)if(!body.some(p=>p.x===x&&p.y===y))free.push({x,y});if(!free.length){end(score,{fruit:score/10,boardCleared:true,perfect:true});return false}fruit=free[Math.floor(Math.random()*free.length)];return true};fruitPlace();
  const turn=(d)=>{if(dir.x+d.x===0&&dir.y+d.y===0)return;queued=d};
  handler=e=>{const k=e.key.toLowerCase();if(['arrowup','w'].includes(k))turn({x:0,y:-1});else if(['arrowdown','s'].includes(k))turn({x:0,y:1});else if(['arrowleft','a'].includes(k))turn({x:-1,y:0});else if(['arrowright','d'].includes(k))turn({x:1,y:0});else return;e.preventDefault()};window.addEventListener('keydown',handler);
  controls([['↑',()=>turn({x:0,y:-1})],['←',()=>turn({x:-1,y:0})],['↓',()=>turn({x:0,y:1})],['→',()=>turn({x:1,y:0})]]);
  const step=()=>{if(dead)return;dir=queued;const head={x:body[0].x+dir.x,y:body[0].y+dir.y};if(head.x<0||head.y<0||head.x>=N||head.y>=N||body.some(p=>p.x===head.x&&p.y===head.y)){end(score,{fruit:score/10});return}body.unshift(head);if(head.x===fruit.x&&head.y===fruit.y){score+=10;sound('eat');if(!fruitPlace())return;timer && clearInterval(timer);timer=setInterval(step,Math.max(65,120-score/5))}else body.pop();updateScore();paint()};
  const paint=()=>{ctx.fillStyle='#10131d';ctx.fillRect(0,0,400,400);ctx.strokeStyle='#ffffff08';for(let i=0;i<=N;i++){ctx.beginPath();ctx.moveTo(i*cell,0);ctx.lineTo(i*cell,400);ctx.stroke();ctx.beginPath();ctx.moveTo(0,i*cell);ctx.lineTo(400,i*cell);ctx.stroke()}ctx.fillStyle='#ff7b9b';ctx.beginPath();ctx.arc(fruit.x*cell+10,fruit.y*cell+10,7,0,Math.PI*2);ctx.fill();body.forEach((p,i)=>{ctx.fillStyle=i?'#a5ca49':'#5fe5ff';ctx.beginPath();ctx.roundRect(p.x*cell+2,p.y*cell+2,16,16,5);ctx.fill()})};paint();timer=setInterval(step,120)
 }
 function runner(){const c=mountCanvas(520,310),ctx=c.getContext('2d');let y=0,vy=0,onGround=true,obstacles=[],frame=0,speed=3,season=0;const jump=()=>{if(onGround){vy=-10.5;onGround=false;sound('tap')}};c.onclick=jump;handler=e=>{if([' ','arrowup','w'].includes(e.key.toLowerCase())){e.preventDefault();jump()}};window.addEventListener('keydown',handler);controls([['JUMP',jump]]);
  const loop=now=>{if(dead)return;raf=requestAnimationFrame(loop);const dt=Math.min(32,now-(frame||now));frame=now;speed+=dt*.0002;const ground=260;y+=vy*(dt/16);if(!onGround)vy+=.55*(dt/16);if(y>=0){y=0;vy=0;onGround=true}spawn+=dt;if(spawn>Math.max(550,1500-speed*100)){obstacles.push({x:550,w:24+Math.random()*20,h:28+Math.random()*34});spawn=0}obstacles.forEach(o=>o.x-=speed*(dt/16));obstacles=obstacles.filter(o=>o.x>-50);score+=dt*.035;const px=75,py=ground-36+y;for(const o of obstacles)if(o.x<px+26&&o.x+o.w>px+5&&py+31>ground-o.h){end(Math.floor(score),{distance:Math.floor(score)});return}
   ctx.clearRect(0,0,520,310);const band=Math.floor(score/100);if(band!==season){season=band;const el=panel.querySelector('#arc-info');if(el)el.textContent=['SPRING','RAIN','WINTER','AUTUMN','NIGHT'][band%5];if(band%5===1)sound('tap')}
   const themes=[['#182336','#91ad56'],['#1c2934','#497978'],['#202945','#b9d7ed'],['#362736','#c7784f'],['#111622','#4e5681']];const [sky,land]=themes[season%5];ctx.fillStyle=sky;ctx.fillRect(0,0,520,ground);ctx.fillStyle=land;ctx.fillRect(0,ground,520,50);ctx.fillStyle='#ffffff22';for(let i=0;i<8;i++){const x=(i*97-(score*3)%97);ctx.fillRect(x,55+(i%3)*35,38,2)}ctx.fillStyle='#5fe5ff';ctx.beginPath();ctx.roundRect(px,py,27,34,8);ctx.fill();ctx.fillStyle='#10131d';ctx.fillRect(px+17,py+8,4,4);obstacles.forEach(o=>{ctx.fillStyle=o.h>50?'#ff7b9b':'#ffbd67';ctx.beginPath();ctx.roundRect(o.x,ground-o.h,o.w,o.h,5);ctx.fill()});ctx.fillStyle='#fff';ctx.font='12px monospace';ctx.fillText(`DISTANCE ${Math.floor(score)} · ENVIRONMENT ${['SPRING','RAIN','WINTER','AUTUMN','NIGHT'][season%5]}`,20,25);updateScore()};raf=requestAnimationFrame(loop)
 }
 function blocks(){const c=mountCanvas(300,600),ctx=c.getContext('2d'),W=10,H=20,grid=Array.from({length:H},()=>Array(W).fill(0));let current=nextPiece(),lines=0,fall=0;function nextPiece(){const i=Math.floor(Math.random()*pieces.length);return {m:clone(pieces[i]),x:3,y:0,color:colors[i]}}function collides(m,x,y){for(let r=0;r<m.length;r++)for(let k=0;k<m[r].length;k++)if(m[r][k]&&(x+k<0||x+k>=W||y+r>=H||(y+r>=0&&grid[y+r][x+k])))return true;return false}function lock(){current.m.forEach((r,y)=>r.forEach((v,x)=>{if(v&&current.y+y>=0)grid[current.y+y][current.x+x]=current.color}));let cleared=0;for(let y=H-1;y>=0;y--)if(grid[y].every(Boolean)){grid.splice(y,1);grid.unshift(Array(W).fill(0));cleared++;y++}if(cleared){lines+=cleared;score+=cleared*cleared*100;sound('success');const e=panel.querySelector('#arc-info');if(e)e.textContent=`LINES ${lines}`}current=nextPiece();if(collides(current.m,current.x,current.y)){end(score,{lines});return}updateScore()}
  const move=(dx,dy=0)=>{if(!collides(current.m,current.x+dx,current.y+dy)){current.x+=dx;current.y+=dy;paint();return true}if(dy){lock();paint()}return false};const rotate=()=>{const m=current.m[0].map((_,i)=>current.m.map(r=>r[i]).reverse());if(!collides(m,current.x,current.y))current.m=m;paint()};const hardDrop=()=>{while(!collides(current.m,current.x,current.y+1))current.y++;lock();paint()};handler=e=>{const k=e.key.toLowerCase();if(['arrowleft','a'].includes(k))move(-1);else if(['arrowright','d'].includes(k))move(1);else if(['arrowdown','s'].includes(k))move(0,1);else if(['arrowup','w','x'].includes(k))rotate();else if(e.code==='Space')hardDrop();else return;e.preventDefault()};window.addEventListener('keydown',handler);controls([['←',()=>move(-1)],['↻',rotate],['→',()=>move(1)],['↓',()=>move(0,1)],['DROP',hardDrop]]);
  function paint(){ctx.fillStyle='#10131d';ctx.fillRect(0,0,300,600);ctx.strokeStyle='#ffffff0c';for(let x=0;x<=W;x++){ctx.beginPath();ctx.moveTo(x*30,0);ctx.lineTo(x*30,600);ctx.stroke()}for(let y=0;y<=H;y++){ctx.beginPath();ctx.moveTo(0,y*30);ctx.lineTo(300,y*30);ctx.stroke()}grid.forEach((row,y)=>row.forEach((v,x)=>v&&block(x,y,v)));current.m.forEach((r,y)=>r.forEach((v,x)=>v&&block(current.x+x,current.y+y,current.color)))}function block(x,y,color){if(y<0)return;ctx.fillStyle=color;ctx.beginPath();ctx.roundRect(x*30+2,y*30+2,26,26,5);ctx.fill();ctx.fillStyle='#ffffff2c';ctx.fillRect(x*30+5,y*30+5,18,3)}
  const tick=()=>{if(dead)return;if(!collides(current.m,current.x,current.y+1))current.y++;else lock();paint()};const interval=()=>Math.max(130,650-lines*48);const schedule=()=>{timer=setTimeout(()=>{tick();if(!dead)schedule()},interval())};schedule();paint()
 }
 drawStart();return {start:run,cleanup};
}
