import {playExtended} from './extended/index.js';

const rand=(n)=>Math.floor(Math.random()*n), choose=a=>a[rand(a.length)], wait=(ms)=>new Promise(r=>setTimeout(r,ms));
const shapes=['●','◆','▲','■','✦','⬟'];
const facts=[['A group of flamingos is called a flamboyance.',true],['Venus is the closest planet to the Sun.',false],['Octopuses have three hearts.',true],['Lightning is hotter than the surface of the Sun.',true],['A snail can sleep for several years.',true],['Goldfish have a three-second memory.',false],['The Great Wall of China is visible from the Moon with the naked eye.',false],['Bananas are berries in botanical terms.',true],['There are more stars than grains of sand on Earth.',true],['Sound travels faster in water than in air.',true]];
const equations=()=>{const a=1+rand(18),b=1+rand(16),op=choose(['+','−','×']);if(op==='+')return[`${a} + ${b}`,a+b];if(op==='−')return[`${Math.max(a,b)} − ${Math.min(a,b)}`,Math.abs(a-b)];const x=1+rand(12),y=1+rand(9);return[`${x} × ${y}`,x*y]};

export function mountCore({panel,game,finish,sound,onStart=()=>{}}){
 let dead=false, done=false, startedAt=0, ids=[], intervals=[], modeCleanup=()=>{};
 const later=(fn,ms)=>{const id=setTimeout(()=>{ids=ids.filter(x=>x!==id);if(!dead)fn()},ms);ids.push(id);return id};
 const every=(fn,ms)=>{const id=setInterval(()=>{if(!dead)fn()},ms);intervals.push(id);return id};
 const clearEvery=id=>{clearInterval(id);intervals=intervals.filter(x=>x!==id)};
 const html=(s)=>{panel.innerHTML=s;panel.classList.add('playing')};
 const finishOnce=(score,extra={})=>{if(dead||done)return;done=true;modeCleanup();ids.forEach(clearTimeout);ids=[];intervals.forEach(clearInterval);intervals=[];sound(score>0?'success':'fail');finish({score:Math.max(0,Math.round(score)),elapsed:Math.max(0,performance.now()-startedAt),...extra})};
 const start=()=>{if(dead||startedAt)return;startedAt=performance.now();sound('tap');onStart(game.category);play()};
 const arena=(height=300)=>`<div class="target-arena" style="height:${height}px"></div>`;
 const startView=()=>{panel.classList.remove('playing');panel.innerHTML=`<div class="eyebrow">${game.category} · ${game.difficulty}</div><h2>${game.title}</h2><p class="instructions">${game.instructions}</p><button class="button primary" id="start-game">PLAY NOW <span>→</span></button><p class="mono muted" style="margin-top:20px">${game.category.toUpperCase()} / QUICK PLAY</p>`;panel.querySelector('#start-game').addEventListener('click',start,{once:true})};
 function play(){
  const mode=game.mode;
  if(mode==='reaction')return reaction(mode);
  if(mode==='flashClick')return flashClick();
  if(mode==='fastestFinger')return fastestFinger();
  if(mode==='stopClock'||mode==='perfectOne')return clock(mode);
  if(mode==='colorMatch')return colorMatch();
  if(mode==='oddOneOut')return oddOneOut();
  if(mode==='quickMath')return quickMath();
  if(mode==='numberMemory')return numberMemory();
  if(mode==='movingTarget')return movingTarget();
  if(mode==='dontClick')return dontClick();
  if(mode==='directionTest')return directionTest();
  if(mode==='numberSequence')return numberSequence();
  if(mode==='tapCounter')return tapCounter();
  if(mode==='patternMemory')return patternMemory();
  if(mode==='memoryGrid')return memoryGrid();
  if(mode==='higherLower')return higherLower();
  if(mode==='trueFalse')return trueFalse();
  if(mode==='shapeMatch')return shapeMatch();
  if(mode==='targetAccuracy'||mode==='bullseye')return targetAccuracy(mode==='bullseye'?1:3);
  if(mode==='visualCount')return visualCount();
  if(mode==='sequenceTap')return sequenceTap();
  if(mode==='redLight')return redLight();
  if(mode==='higherNumber')return comparison(true);
  if(mode==='oddEven')return oddEven();
  if(mode==='colorSequence')return colorSequence();
  if(mode==='coinFlip')return coinFlip();
  if(mode==='avoidWrongObject')return playExtended(mode,{panel,game,later,every,finishOnce,sound,html,setCleanup:fn=>modeCleanup=fn});
  if(mode==='visualCountRush')return playExtended(mode,{panel,game,later,every,finishOnce,sound,html,setCleanup:fn=>modeCleanup=fn});
  if(playExtended(mode,{panel,game,later,every,finishOnce,sound,html,setCleanup:fn=>modeCleanup=fn}))return;
  panel.innerHTML='<h2>Game unavailable</h2><button class="button primary" onclick="location.hash=\'#games\'">Back to games</button>';
 }
 function reaction(mode){let round=0,total=0,armed=false,waitMs=0;html(`<div class="game-hud"><span>ROUND <b id="round">1 / 3</b></span><span id="hint">WAIT FOR GREEN</span></div><div class="prompt-label">${mode==='fastestFinger'?'FAST FINGER':mode==='flashClick'?'FLASH CLICK':'REACTION TEST'}</div><h2 class="big-prompt" id="signal">Ready?</h2><p class="instructions" id="sub">The cue will appear after a random delay.</p><button class="button primary" id="react" disabled>WAIT…</button>`);const b=panel.querySelector('#react'),sig=panel.querySelector('#signal'),sub=panel.querySelector('#sub');const cue=()=>{if(dead)return;armed=true;waitMs=performance.now();panel.classList.add('game-state-green');sig.textContent='GO!';sub.textContent='Tap as fast as you can';b.textContent='TAP NOW';b.disabled=false};const next=()=>{round++;if(round>3){const avg=total/3;finishOnce(Math.max(0,Math.round(1100-avg)),{reactionTime:Math.round(avg),perfect:avg<220});return}panel.querySelector('#round').textContent=`${round} / 3`;armed=false;panel.classList.remove('game-state-green');sig.textContent='Ready?';sub.textContent='The cue will appear after a random delay.';b.disabled=false;b.textContent='WAIT…';later(cue,900+rand(2100))};b.addEventListener('click',()=>{if(!startedAt||done)return;if(!armed){sound('fail');finishOnce(0,{falseStart:true});return}total+=performance.now()-waitMs;sound('success');next()});next()}
 function flashClick(){let armed=false,at=0;html(`<div class="prompt-label">WAIT FOR THE FLASH</div><div class="target-arena" id="flash-arena" style="display:grid;place-items:center"><div class="big-prompt" id="flash-signal">…</div></div><p class="instructions">Tap anywhere in the arena as soon as it lights up.</p>`);const a=panel.querySelector('#flash-arena');a.onclick=()=>{if(!armed){finishOnce(0,{falseStart:true});return}const ms=performance.now()-at;finishOnce(Math.max(0,1000-Math.round(ms)),{reactionTime:Math.round(ms),perfect:ms<210})};later(()=>{if(dead)return;armed=true;at=performance.now();a.classList.add('game-state-green');panel.querySelector('#flash-signal').textContent='FLASH!';later(()=>{if(!done)finishOnce(0,{missed:true})},1800)},800+rand(2200))}
 function fastestFinger(){let armed=false,at=0;html(`<div class="prompt-label">WAIT FOR YOUR BUTTON</div>${arena(290)}<p class="instructions">The target will appear in a different spot. Hit it fast.</p>`);const a=panel.querySelector('.target-arena');a.onclick=e=>{if(e.target===a&&!armed)finishOnce(0,{falseStart:true})};later(()=>{if(dead)return;armed=true;at=performance.now();const b=document.createElement('button');b.className='target';b.style.left=`${rand(Math.max(1,a.clientWidth-50))}px`;b.style.top=`${rand(Math.max(1,a.clientHeight-50))}px`;b.setAttribute('aria-label','Hit the target');a.append(b);b.onclick=e=>{e.stopPropagation();const ms=performance.now()-at;finishOnce(Math.max(0,1000-Math.round(ms)),{reactionTime:Math.round(ms),perfect:ms<210})};later(()=>finishOnce(0,{missed:true}),1500)},850+rand(2000))}
 function clock(mode){const target=mode==='perfectOne'?1000:5000;html(`<div class="prompt-label">STOP AT ${mode==='perfectOne'?'1.00':'5.00'} SECONDS</div><div class="big-prompt" id="time-display">${(target/1000).toFixed(2)}</div><p class="instructions" id="clock-hint">Press start, then stop as close to the target as you can.</p><button class="button primary" id="clock-btn">START CLOCK</button>`);const btn=panel.querySelector('#clock-btn'),display=panel.querySelector('#time-display'),hint=panel.querySelector('#clock-hint');let t=0,raf=0,active=false;btn.onclick=()=>{if(!active){t=performance.now();active=true;btn.textContent='STOP';hint.textContent='Tap to stop the clock';const tick=()=>{if(dead||!active)return;display.textContent=((performance.now()-t)/1000).toFixed(2);raf=requestAnimationFrame(tick)};tick()}else{active=false;cancelAnimationFrame(raf);const elapsed=performance.now()-t,diff=Math.abs(elapsed-target),score=Math.max(0,1000-Math.round(diff*(mode==='perfectOne'?1.5:.2)));display.textContent=(elapsed/1000).toFixed(3);hint.textContent=`${(diff/1000).toFixed(3)} seconds away`;btn.disabled=true;later(()=>finishOnce(score,{difference:Math.round(diff),perfect:diff<=15}),650)}};modeCleanup=()=>cancelAnimationFrame(raf)}
 function colorMatch(){let n=0,score=0,delay=0;const colors=[['RED','#ff657a'],['BLUE','#68a5ff'],['GREEN','#8ddf75'],['PURPLE','#ba8aff']];function question(){if(n>=8)return finishOnce(score*125,{correct:score,rounds:8,perfect:score===8});n++;let word=choose(colors),ink=choose(colors);while(ink===word)ink=choose(colors);html(`<div class="game-hud"><span>ROUND ${n} / 8</span><span>${score} CORRECT</span></div><div class="prompt-label">TAP THE INK COLOR</div><div class="big-prompt" style="color:${ink[1]}">${word[0]}</div><p class="instructions">Ignore what the word says. Follow its color.</p><div class="answer-row">${colors.map(c=>`<button class="answer-btn color-answer" aria-label="${c[0]}" data-c="${c[0]}" style="background:${c[1]}"></button>`).join('')}</div>`);panel.querySelectorAll('[data-c]').forEach(b=>b.onclick=()=>{if(delay)return;delay=1;if(b.dataset.c===ink[0]){score++;sound('success')}else sound('fail');later(()=>{delay=0;question()},150)})}question()}
 function oddOneOut(){let n=0,score=0;function question(){if(n>=7)return finishOnce(score*140,{correct:score,rounds:7,perfect:score===7});n++;const size=n<3?3:4,total=size*size,odd=rand(total),base=choose(shapes),diff=choose(shapes.filter(x=>x!==base));html(`<div class="game-hud"><span>ROUND ${n} / 7</span><span>STREAK ${score}</span></div><div class="prompt-label">FIND THE ODD SYMBOL</div><div class="sequence-grid" style="grid-template-columns:repeat(${size},minmax(44px,min(75px,18vw)))">${Array.from({length:total},(_,i)=>`<button class="sequence-cell" data-i="${i}">${i===odd?diff:base}</button>`).join('')}</div>`);panel.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>{if(n===0)return;if(Number(b.dataset.i)===odd){score++;sound('success')}else sound('fail');n=Number(n);nextAfter(question)})}let locked=false;function nextAfter(fn){if(locked)return;locked=true;later(()=>{locked=false;question()},160)}question()}
 function quickMath(){let score=0,answered=0,seconds=20;const deadline=performance.now()+seconds*1000;html(`<div class="game-hud"><span id="math-time">20s</span><span id="math-score">0 PTS</span></div><div class="prompt-label">SOLVE FAST</div><div class="big-prompt" id="equation"></div><div class="answer-row" id="math-answers"></div>`);function q(){if(performance.now()>=deadline)return finishOnce(score,{correct:answered,perfect:score>=1200});const [eq,ans]=equations(),opts=new Set([ans]);while(opts.size<4)opts.add(Math.max(0,ans+rand(15)-7));const choices=[...opts].sort(()=>Math.random()-.5);panel.querySelector('#equation').textContent=eq;panel.querySelector('#math-answers').innerHTML=choices.map(v=>`<button class="answer-btn" data-a="${v}">${v}</button>`).join('');panel.querySelectorAll('[data-a]').forEach(b=>b.onclick=()=>{if(Number(b.dataset.a)===ans){score+=100;answered++;sound('success')}else sound('fail');panel.querySelector('#math-score').textContent=`${score} PTS`;q()})}q();every(()=>{const left=Math.max(0,(deadline-performance.now())/1000);const el=panel.querySelector('#math-time');if(el)el.textContent=`${left.toFixed(1)}s`;if(left<=0)finishOnce(score,{correct:answered})},80)}
 function numberMemory(){const len=4+rand(2),num=Array.from({length:len},()=>rand(10)).join('');html(`<div class="prompt-label">MEMORIZE THIS NUMBER</div><div class="big-prompt" id="mem-num">${num}</div><p class="instructions">You have ${Math.max(1.5,len*.48).toFixed(1)} seconds</p>`);later(()=>{if(dead)return;html(`<div class="prompt-label">TYPE THE NUMBER</div><p class="instructions">Enter the digits you saw.</p><input class="game-input" id="mem-input" inputmode="numeric" autocomplete="off" maxlength="12" aria-label="Enter remembered number"><button class="button primary" id="mem-submit" style="margin-top:14px">CHECK</button>`);const input=panel.querySelector('#mem-input');input.focus();const check=()=>{const ok=input.value===num;sound(ok?'success':'fail');finishOnce(ok?len*180:0,{correct:ok?1:0,digits:len,perfect:ok})};panel.querySelector('#mem-submit').onclick=check;input.onkeydown=e=>{if(e.key==='Enter')check()}},Math.max(1600,len*480))}
 function movingTarget(){let hits=0,total=0;html(`<div class="game-hud"><span id="hits">TARGETS 0 / 8</span><span id="elapsed">QUICK FEET</span></div><div class="prompt-label">HIT EVERY TARGET</div>${arena(290)}`);const a=panel.querySelector('.target-arena');const place=()=>{let t=a.querySelector('.target');if(!t){t=document.createElement('button');t.className='target';t.setAttribute('aria-label','Target');a.append(t)}t.style.left=`${rand(Math.max(1,a.clientWidth-50))}px`;t.style.top=`${rand(Math.max(1,a.clientHeight-50))}px`;t.onclick=e=>{e.stopPropagation();const now=performance.now();total+=now-(t._at||now);hits++;sound('success');panel.querySelector('#hits').textContent=`TARGETS ${hits} / 8`;if(hits===8)finishOnce(Math.max(0,1500-Math.round((performance.now()-startedAt)/5)),{targets:hits,perfect:performance.now()-startedAt<6500});else place();t._at=performance.now()};t._at=performance.now()};place();every(()=>{const t=a.querySelector('.target');if(t&&hits<8&&performance.now()-t._at>1600){place()}},450)}
 function dontClick(){const duration=2500+rand(3501),seconds=(duration/1000).toFixed(1);html(`<div class="prompt-label">THE BUTTON IS BAIT</div><div class="big-prompt" id="countdown">${seconds}</div><p class="instructions">Resist the button for a randomly timed countdown.</p><button class="button primary" id="bait">DON’T CLICK</button>`);const deadline=performance.now()+duration;panel.querySelector('#bait').onclick=()=>finishOnce(0,{resisted:false});const it=every(()=>{const left=Math.max(0,deadline-performance.now());const el=panel.querySelector('#countdown');if(el)el.textContent=(left/1000).toFixed(1);if(left<=0)finishOnce(1000,{resisted:true,perfect:true})},30)}
 function directionTest(){let n=0,score=0;const directions=[['↑','UP'],['↓','DOWN'],['←','LEFT'],['→','RIGHT']];function q(){if(n>=10)return finishOnce(score*100,{correct:score,rounds:10,perfect:score===10});n++;const d=choose(directions);html(`<div class="game-hud"><span>ROUND ${n} / 10</span><span>${score} RIGHT</span></div><div class="prompt-label">FOLLOW THE ARROW</div><div class="big-prompt">${d[0]}</div><div class="answer-row">${directions.map(x=>`<button class="answer-btn" data-v="${x[1]}">${x[1]}</button>`).join('')}</div>`);panel.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>{if(b.dataset.v===d[1]){score++;sound('success')}else sound('fail');later(q,100)})}q()}
 function numberSequence(){let n=0,score=0;function q(){if(n>=6)return finishOnce(score*165,{correct:score,rounds:6,perfect:score===6});n++;const a=2+rand(9),step=1+rand(7),seq=[a,a+step,a+step*2,a+step*3],ans=a+step*4,opts=new Set([ans]);while(opts.size<4)opts.add(ans+rand(17)-8);html(`<div class="game-hud"><span>ROUND ${n} / 6</span><span>${score} SOLVED</span></div><div class="prompt-label">WHAT COMES NEXT?</div><div class="big-prompt" style="font-size:clamp(34px,8vw,70px)">${seq.join(' · ')} · ?</div><div class="answer-row">${[...opts].sort(()=>Math.random()-.5).map(x=>`<button class="answer-btn" data-a="${x}">${x}</button>`).join('')}</div>`);panel.querySelectorAll('[data-a]').forEach(b=>b.onclick=()=>{if(Number(b.dataset.a)===ans){score++;sound('success')}else sound('fail');later(q,120)})}q()}
 function tapCounter(){let count=0;const end=performance.now()+7000;html(`<div class="game-hud"><span id="tap-timer">7.0s</span><span>VALID TAPS <b id="tap-count">0</b></span></div><div class="prompt-label">GO GO GO</div><button class="answer-btn" id="tap-zone" style="width:min(270px,80vw);height:190px;font-size:35px;border-radius:25px">TAP!</button><p class="instructions">One press counts once. No double-click bonus.</p>`);const zone=panel.querySelector('#tap-zone');zone.addEventListener('pointerdown',e=>{e.preventDefault();if(performance.now()>=end)return;count++;panel.querySelector('#tap-count').textContent=count;sound('tap')});every(()=>{const left=Math.max(0,(end-performance.now())/1000),el=panel.querySelector('#tap-timer');if(el)el.textContent=`${left.toFixed(1)}s`;if(left<=0)finishOnce(count*35,{taps:count,perfect:count>=35})},30)}
 function patternMemory(){const size=4,cells=16,count=3+rand(3),picked=new Set();while(picked.size<count)picked.add(rand(cells));html(`<div class="prompt-label">MEMORIZE THE LIT TILES</div><div class="tile-grid">${Array.from({length:cells},(_,i)=>`<div class="tile ${picked.has(i)?'on':''}"></div>`).join('')}</div><p class="instructions">Pattern disappears in a moment…</p>`);later(()=>{html(`<div class="prompt-label">REBUILD THE PATTERN</div><div class="tile-grid">${Array.from({length:cells},(_,i)=>`<button class="tile" data-i="${i}" aria-label="Tile ${i+1}"></button>`).join('')}</div><button class="button primary" id="grid-check">CHECK PATTERN</button>`);const selected=new Set();panel.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.i);if(selected.has(i)){selected.delete(i);b.classList.remove('selected')}else{selected.add(i);b.classList.add('selected')}});panel.querySelector('#grid-check').onclick=()=>{const correct=[...picked].filter(i=>selected.has(i)).length,exact=correct===count&&selected.size===count;sound(exact?'success':'fail');finishOnce(Math.round(correct/count*1000-(selected.size-count)*70),{correct,tiles:count,perfect:exact})}},1650)}
 function memoryGrid(){const len=5+rand(2),seq=[],used=new Set();while(seq.length<len){const x=rand(25);if(!used.has(x)){used.add(x);seq.push(x)}}html(`<div class="prompt-label">FOLLOW THE LIGHTS IN ORDER</div><div class="tile-grid" id="memory-grid" style="grid-template-columns:repeat(5,minmax(42px,60px))">${Array.from({length:25},(_,i)=>`<div class="tile" data-cell="${i}"></div>`).join('')}</div><p class="instructions">${len} cells will light up, one at a time.</p>`);let i=0;const flash=()=>{if(i>=len)return later(input,350);const cell=panel.querySelector(`[data-cell="${seq[i]}"]`);if(!cell)return;cell.classList.add('on');later(()=>{cell.classList.remove('on');i++;later(flash,140)},350)};const input=()=>{let step=0;html(`<div class="game-hud"><span>STEP <b id="grid-step">1 / ${len}</b></span></div><div class="prompt-label">REPEAT THE ORDER</div><div class="tile-grid" style="grid-template-columns:repeat(5,minmax(42px,60px))">${Array.from({length:25},(_,x)=>`<button class="tile" data-cell="${x}" aria-label="Cell ${x+1}"></button>`).join('')}</div>`);panel.querySelectorAll('[data-cell]').forEach(b=>b.onclick=()=>{if(Number(b.dataset.cell)!==seq[step]){finishOnce(step*150,{correct:step,sequenceLength:len});return}b.classList.add('on');sound('tap');step++;const label=panel.querySelector('#grid-step');if(step<len&&label)label.textContent=`${step+1} / ${len}`;if(step===len)finishOnce(1000+len*100,{correct:len,perfect:true})})};later(flash,400)}
 function higherLower(){let cur=1+rand(99),n=0,streak=0,best=0;function q(){if(n>=8)return finishOnce(best*150,{correct:streak,rounds:8,streak:best,perfect:best===8});n++;let next=1+rand(99);while(next===cur)next=1+rand(99);html(`<div class="game-hud"><span>ROUND ${n} / 8</span><span>BEST STREAK ${best}</span></div><div class="prompt-label">HIGHER OR LOWER THAN</div><div class="big-prompt">${cur}</div><div class="answer-row"><button class="answer-btn" data-v="higher">↑ HIGHER</button><button class="answer-btn" data-v="lower">↓ LOWER</button></div>`);panel.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>{const ok=b.dataset.v===(next>cur?'higher':'lower');if(ok){streak++;best=Math.max(best,streak);sound('success')}else{streak=0;sound('fail')}cur=next;later(q,120)})}q()}
 function trueFalse(){let n=0,score=0,bag=[...facts].sort(()=>Math.random()-.5);function q(){if(n>=8)return finishOnce(score*125,{correct:score,rounds:8,perfect:score===8});n++;const [statement,truth]=bag[(n-1)%bag.length];html(`<div class="game-hud"><span>QUESTION ${n} / 8</span><span>${score} CORRECT</span></div><div class="prompt-label">TRUE OR FALSE?</div><h2 style="max-width:560px;line-height:1.25">${statement}</h2><div class="answer-row"><button class="answer-btn" data-v="true">TRUE</button><button class="answer-btn" data-v="false">FALSE</button></div>`);panel.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>{if((b.dataset.v==='true')===truth){score++;sound('success')}else sound('fail');later(q,130)})}q()}
 function shapeMatch(){let n=0,score=0;function q(){if(n>=8)return finishOnce(score*125,{correct:score,rounds:8,perfect:score===8});n++;const target=choose(shapes),opts=new Set([target]);while(opts.size<4)opts.add(choose(shapes));const answers=[...opts].sort(()=>Math.random()-.5);html(`<div class="game-hud"><span>ROUND ${n} / 8</span><span>${score} MATCHED</span></div><div class="prompt-label">MATCH THIS SHAPE</div><div class="big-prompt">${target}</div><div class="answer-row">${answers.map((x,i)=>`<button class="answer-btn" data-v="${x}" style="font-size:34px;width:70px;height:70px">${x}</button>`).join('')}</div>`);panel.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>{if(b.dataset.v===target){score++;sound('success')}else sound('fail');later(q,120)})}q()}
 function targetAccuracy(shots){let n=0,total=0;function shot(){n++;html(`<div class="game-hud"><span>SHOT ${n} / ${shots}</span><span>HIT THE CENTER</span></div><div class="prompt-label">PRECISION COUNTS</div>${arena(300)}`);const a=panel.querySelector('.target-arena'),t=document.createElement('button');t.className='target';t.style.width='100px';t.style.height='100px';t.style.left=`${rand(Math.max(1,a.clientWidth-105))}px`;t.style.top=`${rand(Math.max(1,a.clientHeight-105))}px`;t.style.background='radial-gradient(circle,var(--lime) 0 8%,#cf536a 9% 20%,var(--lime) 21% 38%,#cf536a 39% 53%,var(--lime) 54%)';t.setAttribute('aria-label','Bullseye target');a.append(t);a.onclick=e=>{if(e.target!==a&&e.target!==t)return;const r=t.getBoundingClientRect(),dx=e.clientX-(r.left+r.width/2),dy=e.clientY-(r.top+r.height/2),dist=Math.min(1,Math.hypot(dx,dy)/(Math.min(r.width,r.height)/2)),points=Math.max(0,Math.round((1-dist)*1000));total+=points;sound(points>500?'success':'tap');if(n>=shots)finishOnce(Math.round(total/shots),{accuracy:Math.round(total/shots),shots,perfect:total/shots>950});else later(shot,180)};t.onclick=e=>{e.stopPropagation();if(done||dead)return;const r=t.getBoundingClientRect(),dx=e.clientX-(r.left+r.width/2),dy=e.clientY-(r.top+r.height/2),dist=Math.min(1,Math.hypot(dx,dy)/(Math.min(r.width,r.height)/2)),points=Math.max(0,Math.round((1-dist)*1000));total+=points;sound(points>500?'success':'tap');if(n>=shots)finishOnce(Math.round(total/shots),{accuracy:Math.round(total/shots),shots,perfect:total/shots>950});else later(shot,180)}}shot()}
 function visualCount(){let n=0,total=0;function q(){if(n>=5)return finishOnce(total*200,{correct:total,rounds:5,perfect:total===5});n++;const count=3+rand(9);html(`<div class="game-hud"><span>ROUND ${n} / 5</span><span>${total} CORRECT</span></div><div class="prompt-label">HOW MANY DOTS?</div><div style="display:grid;grid-template-columns:repeat(5,30px);gap:12px;margin:26px auto">${Array.from({length:count},()=>'<span style="height:22px;width:22px;border-radius:50%;background:var(--cyan)"></span>').join('')}</div><p class="instructions">Look quickly…</p>`);later(()=>{html(`<div class="prompt-label">HOW MANY DID YOU SEE?</div><div class="answer-row">${[...new Set([count,Math.max(1,count-1),count+1,Math.max(1,count+2)])].sort(()=>Math.random()-.5).map(x=>`<button class="answer-btn" data-v="${x}">${x}</button>`).join('')}</div>`);panel.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>{if(Number(b.dataset.v)===count){total++;sound('success')}else sound('fail');later(q,140)})},900)}q()}
 function sequenceTap(){const seq=Array.from({length:5},()=>1+rand(9));html(`<div class="prompt-label">MEMORIZE THE ORDER</div><div class="big-prompt">${seq.join('  ·  ')}</div><p class="instructions">The numbers disappear shortly.</p>`);later(()=>{let i=0;html(`<div class="game-hud"><span>STEP <b id="seq-step">1 / 5</b></span></div><div class="prompt-label">TAP IN ORDER</div><div class="sequence-grid">${Array.from({length:9},(_,x)=>`<button class="sequence-cell" data-v="${x+1}">${x+1}</button>`).join('')}</div>`);panel.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>{if(Number(b.dataset.v)===seq[i]){i++;sound('success');const h=panel.querySelector('#seq-step');if(h&&i<5)h.textContent=`${i+1} / 5`;if(i===5)finishOnce(1000,{correct:5,perfect:true})}else{sound('fail');finishOnce(i*200,{correct:i,perfect:false})}})},1700)}
 function redLight(){let round=0,total=0,greenAt=0,armed=false;function next(){if(round>=3){const avg=total/3;return finishOnce(Math.max(0,1000-Math.round(avg)),{reactionTime:Math.round(avg),perfect:avg<240})}round++;armed=false;html(`<div class="game-hud"><span>ROUND ${round} / 3</span><span>WAIT FOR GREEN</span></div><div class="target-arena game-state-red" id="light-arena" style="display:grid;place-items:center"><div class="big-prompt" id="light-signal">RED LIGHT</div></div><p class="instructions">Tap only after it turns green.</p>`);const a=panel.querySelector('#light-arena');a.onclick=()=>{if(!armed){sound('fail');finishOnce(0,{falseStart:true});return}total+=performance.now()-greenAt;sound('success');next()};later(()=>{if(dead)return;armed=true;greenAt=performance.now();a.classList.remove('game-state-red');a.classList.add('game-state-green');panel.querySelector('#light-signal').textContent='GREEN!'},1000+rand(2000))}next()}
 function comparison(larger){let n=0,score=0;function q(){if(n>=10)return finishOnce(score*100,{correct:score,rounds:10,perfect:score===10});n++;const a=1+rand(99);let b=1+rand(99);while(a===b)b=1+rand(99);const correct=larger?Math.max(a,b):Math.min(a,b);html(`<div class="game-hud"><span>ROUND ${n} / 10</span><span>${score} RIGHT</span></div><div class="prompt-label">CHOOSE THE ${larger?'LARGER':'SMALLER'} NUMBER</div><div class="answer-row"><button class="answer-btn" data-v="${a}" style="font-size:30px;min-width:110px">${a}</button><button class="answer-btn" data-v="${b}" style="font-size:30px;min-width:110px">${b}</button></div>`);panel.querySelectorAll('[data-v]').forEach(x=>x.onclick=()=>{if(Number(x.dataset.v)===correct){score++;sound('success')}else sound('fail');later(q,100)})}q()}
 function oddEven(){let n=0,score=0;function q(){if(n>=10)return finishOnce(score*100,{correct:score,rounds:10,perfect:score===10});n++;const x=1+rand(199);html(`<div class="game-hud"><span>ROUND ${n} / 10</span><span>${score} RIGHT</span></div><div class="prompt-label">ODD OR EVEN?</div><div class="big-prompt">${x}</div><div class="answer-row"><button class="answer-btn" data-v="odd">ODD</button><button class="answer-btn" data-v="even">EVEN</button></div>`);panel.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>{if(b.dataset.v===(x%2?'odd':'even')){score++;sound('success')}else sound('fail');later(q,100)})}q()}
 function colorSequence(){const colors=['#ff6b7c','#7daaff','#a9e670','#ae91ff'];const seq=Array.from({length:4+rand(2)},()=>rand(4));html(`<div class="prompt-label">WATCH THE COLOR SEQUENCE</div><div class="answer-row" id="color-flash">${seq.map(x=>`<div style="width:48px;height:48px;border-radius:14px;background:${colors[x]};opacity:.35"></div>`).join('')}</div><p class="instructions">Memorize the order.</p>`);let i=0;const flash=()=>{if(i>=seq.length)return later(()=>input(),250);const children=panel.querySelector('#color-flash')?.children;if(!children)return;children[seq[i]].style.opacity='1';children[seq[i]].style.transform='scale(1.2)';later(()=>{if(children[seq[i]]){children[seq[i]].style.opacity='.35';children[seq[i]].style.transform=''}i++;later(flash,170)},300)};const input=()=>{let step=0;html(`<div class="game-hud"><span>STEP <b id="color-step">1 / ${seq.length}</b></span></div><div class="prompt-label">REPEAT THE SEQUENCE</div><div class="answer-row">${colors.map((c,x)=>`<button class="answer-btn color-answer" data-v="${x}" style="background:${c}" aria-label="Color ${x+1}"></button>`).join('')}</div>`);panel.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>{const correct=Number(b.dataset.v)===seq[step];if(!correct){sound('fail');finishOnce(step*180,{correct:step,sequenceLength:seq.length});return}step++;sound('tap');if(step===seq.length){sound('success');finishOnce(1000+step*80,{correct:step,perfect:true})}else panel.querySelector('#color-step').textContent=`${step+1} / ${seq.length}`})};later(flash,350)}
 function coinFlip(){let n=0,streak=0;function q(){if(n>=8)return finishOnce(streak*160,{streak,correct:streak,rounds:8,perfect:streak===8});n++;const flip=choose(['heads','tails']);html(`<div class="game-hud"><span>FLIP ${n} / 8</span><span>STREAK ${streak}</span></div><div class="prompt-label">CALL THE FLIP</div><div class="big-prompt">🪙</div><div class="answer-row"><button class="answer-btn" data-v="heads">HEADS</button><button class="answer-btn" data-v="tails">TAILS</button></div>`);panel.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>{if(b.dataset.v===flip){streak++;sound('success')}else{sound('fail');finishOnce(streak*160,{streak,correct:streak,perfect:false});return}later(q,130)})}q()}
 startView();
 return {start,cleanup(){if(dead)return;dead=true;done=true;modeCleanup();ids.forEach(clearTimeout);intervals.forEach(clearInterval);panel.classList.remove('playing')}};
}
