const core = [
  ['reaction-test','Reaction Test','Reaction','⚡','Measure your reflexes in milliseconds.','reaction','Wait for green. Tap as soon as it appears.'],
  ['stop-the-clock','Stop the Clock','Accuracy','⏱️','Land as close as you can to five seconds.','stopClock','Start the clock, then stop it at exactly 5.00 seconds.'],
  ['color-match','Color Match','Vision','🎨','Follow the rule, not the word.','colorMatch','Choose the ink color when the word and ink disagree.'],
  ['odd-one-out','Odd One Out','Vision','🔎','Spot the symbol that breaks the pattern.','oddOneOut','Tap the one symbol that is different.'],
  ['quick-math','Quick Math','Math','➗','Solve as many as you can before time runs out.','quickMath','Choose the correct answer before the timer ends.'],
  ['number-memory','Number Memory','Memory','🔢','How many digits can you hold onto?','numberMemory','Memorize the number, then type it back.'],
  ['moving-target','Moving Target','Accuracy','🎯','Track down targets before they move.','movingTarget','Hit every target as quickly as possible.'],
  ['dont-click','Don’t Click','Fun','🤫','A decoy moves beside the safe target.','avoidWrongObject','Tap the safe object. Hitting a decoy ends the run.'],
  ['direction-test','Direction Test','Speed','↗️','React to the arrow before it flips.','directionTest','Tap the direction shown by the arrow.'],
  ['number-sequence','Number Sequence','Logic','🧩','Find the rule and finish the sequence.','numberSequence','Choose the number that comes next.'],
  ['tap-counter','Tap Counter','Speed','👆','A short burst. How fast are you?','tapCounter','Tap as many times as possible while the timer runs.'],
  ['pattern-memory','Pattern Memory','Memory','▦','Watch the tiles. Repeat the pattern.','patternMemory','Remember the highlighted cells and repeat them.'],
  ['higher-or-lower','Higher or Lower','Luck','⬆️','Keep your streak alive with one good guess.','higherLower','Predict whether the next number will be higher or lower.'],
  ['true-or-false','True or False','Logic','✓','Quick facts. Trust your first instinct.','trueFalse','Decide if each statement is true or false.'],
  ['shape-match','Shape Match','Vision','🔷','Find the shape that matches the target.','shapeMatch','Tap the exact same shape and color.'],
  ['target-accuracy','Target Accuracy','Accuracy','◎','Three shots. Make every pixel count.','targetAccuracy','Tap the center of each target. Closer scores more.'],
  ['fastest-finger','Fastest Finger','Reaction','☝️','A random cue, one fast response.','fastestFinger','Wait for the cue, then tap the button.'],
  ['visual-counting','Visual Counting','Vision','👀','Count the dots before they disappear.','visualCount','Count the dots, then choose the total.'],
  ['sequence-tap','Sequence Tap','Memory','1️⃣','Remember the order. Tap it back.','sequenceTap','Watch the numbered tiles, then repeat the sequence.'],
  ['memory-grid','Memory Grid','Memory','▦','Follow the flashes, then replay their path.','memoryGrid','Watch each tile light up, then tap the sequence in order.'],
  ['flash-click','Flash Click','Reaction','✨','A flash appears. Catch it instantly.','flashClick','Wait for the flash, then tap anywhere in the arena.'],
  ['red-light','Red Light','Reaction','🟢','Green means go. Red means wait.','redLight','Tap only when the arena is green. Red ends the run.'],
  ['bullseye','Bullseye','Accuracy','🎯','Put your shot right in the middle.','bullseye','Click the center of the target for a perfect score.'],
  ['perfect-1-second','Perfect 1.00','Accuracy','⏲️','Can you stop the clock at exactly 1.00?','perfectOne','Tap when you think exactly one second has passed.'],
  ['higher-number','Higher Number','Math','↗️','Pick the larger number before time runs out.','higherNumber','Tap the larger of the two numbers.'],
  ['odd-or-even','Odd or Even','Math','🔣','Sort the number before the clock hits zero.','oddEven','Choose whether the displayed number is odd or even.'],
  ['color-sequence','Color Sequence','Memory','🌈','Repeat a growing chain of colors.','colorSequence','Watch the color sequence, then repeat it.'],
  ['coin-flip-streak','Coin Flip Streak','Luck','🪙','Call the flip. Keep the streak alive.','coinFlip','Predict heads or tails, then continue your streak.'],
  ['mini-runner','Endless Runner','Arcade','🏃','Jump over obstacles. How far can you make it?','runner','Tap, click, Space, or ↑ to jump over obstacles.'],
  ['snake','Snake','Arcade','🐍','Eat, grow, and stay out of your own way.','snake','Use arrow keys, WASD, or the on-screen controls.'],
  ['block-stack','Block Stack','Arcade','🟪','Fit falling blocks and clear complete rows.','blocks','← → move · ↑ rotate · ↓ drop · Space hard drop.']
];

const more = [
  ['quick-draw','Quick Draw','Reaction','⚡','Pick the correct target the instant it appears.','quickDraw','Wait for the signal, then tap the matching target.'],
  ['lightning-tap','Lightning Tap','Reaction','🌩️','Catch a run of fast flashes before they vanish.','lightningTap','Tap each flash as it lights up.'],
  ['instant-button','Instant Button','Reaction','🔘','The button lands somewhere new every round.','instantButton','Wait, then hit the button wherever it appears.'],
  ['reaction-chain','Reaction Chain','Reaction','🔗','React to the right cues and ignore the decoys.','reactionChain','Tap on green. Do nothing on red.'],
  ['wait-for-it','Wait For It','Reaction','⌛','One cue. One chance to wait for the right moment.','waitForIt','Click only after the cue changes.'],
  ['speed-switch','Speed Switch','Reaction','🔀','Follow the changing signal before it flips again.','speedSwitch','Choose the matching direction as quickly as you can.'],
  ['fast-finger','Fast Finger','Reaction','☝️','Hit the target before its short window closes.','fastFinger','Tap the target before it disappears.'],
  ['blink-catcher','Blink Catcher','Reaction','👁️','A blink-and-you-miss-it target appears once.','blinkCatcher','Catch the target during its brief appearance.'],
  ['tiny-target','Tiny Target','Accuracy','🔬','Targets shrink with each precise hit.','tinyTarget','Hit five targets as they get smaller.'],
  ['moving-bullseye','Moving Bullseye','Accuracy','🎯','Track a moving bullseye and land three shots.','movingBullseye','Tap the moving target as close to its center as you can.'],
  ['three-shots','Three Shots','Accuracy','🔫','Exactly three chances to score.','threeShots','Take three shots. Each click scores by distance from center.'],
  ['perfect-center','Perfect Center','Accuracy','⏹️','Stop the moving marker inside the center zone.','perfectCenter','Stop the moving marker when it enters the bright center.'],
  ['target-rain','Target Rain','Accuracy','🌧️','Targets keep appearing. Score before time runs out.','targetRain','Tap as many targets as you can in ten seconds.'],
  ['one-shot','One Shot','Accuracy','🎯','One click decides the whole round.','oneShot','Click once inside the target. Closer to the center scores more.'],
  ['safe-zone','Safe Zone','Accuracy','🟢','Stop the moving marker inside the shrinking safe zone.','safeZone','Tap when the marker overlaps the safe zone.'],
  ['avoid-red','Avoid the Red','Accuracy','🔵','Blue targets score. Red targets end your run.','avoidRed','Tap blue targets and avoid red ones.'],
  ['precision-line','Precision Line','Accuracy','📏','Stop a sweeping line inside a narrow scoring band.','precisionLine','Tap to stop the line while it crosses the highlighted band.'],
  ['find-the-dot','Find the Dot','Vision','🔍','One dot has a slightly different size. Find it.','findDot','Tap the dot that is different from the others.'],
  ['which-shape','Which Shape?','Vision','🔺','Match a silhouette among similar shapes.','whichShape','Choose the exact shape shown in the target.'],
  ['color-intruder','Color Intruder','Vision','🟣','Spot the subtly different color in each round.','colorIntruder','Tap the tile with the slightly different hue.'],
  ['missing-tile','Missing Tile','Vision','🧱','Remember the complete grid and find the removed tile.','missingTile','Study the grid, then choose where the missing tile was.'],
  ['mirror-image','Mirror Image','Vision','🪞','One shape pair is flipped the wrong way.','mirrorImage','Find the pair that is not a true mirror match.'],
  ['flash-memory','Flash Memory','Vision','⚡','Remember a flash location and tap it back.','flashMemory','Watch where the flash appears, then tap that cell.'],
  ['same-or-different','Same or Different','Vision','👁️','Compare two patterns before they disappear.','sameDifferent','Decide whether the two patterns match exactly.'],
  ['hidden-number','Hidden Number','Vision','🔢','Find the number hiding among distracting symbols.','hiddenNumber','Tap the only number among the letter-like symbols.'],
  ['pixel-hunt','Pixel Hunt','Vision','🟪','Find the one tile with a different shade.','pixelHunt','Tap the square whose color differs from the rest.'],
  ['flash-numbers','Flash Numbers','Memory','💡','Remember longer numbers as the rounds advance.','flashNumbers','Memorize the number and enter it after it disappears.'],
  ['icon-sequence','Icon Sequence','Memory','🧸','Watch a growing icon sequence and repeat it.','iconSequence','Tap the icons in the order they light up.'],
  ['card-peek','Card Peek','Memory','🃏','Peek at the cards, then find the requested symbol.','cardPeek','Remember the card locations and select the named card.'],
  ['position-memory','Position Memory','Memory','📍','Recall the last position of a moving marker.','positionMemory','Watch the marker travel, then select its final position.'],
  ['reverse-memory','Reverse Memory','Memory','🔁','Recall the sequence backwards.','reverseMemory','Memorize the digits, then enter them in reverse order.'],
  ['memory-pair','Memory Pair','Memory','🂠','Find the matching pair with as few flips as possible.','memoryPair','Flip cards two at a time and locate the matching pair.'],
  ['vanishing-grid','Vanishing Grid','Memory','▦','Rebuild a larger highlighted pattern each level.','vanishingGrid','Remember every highlighted cell and recreate the pattern.'],
  ['what-changed','What Changed?','Memory','🕵️','Spot the object that changed between two scenes.','whatChanged','Compare both scenes and select the changed object.'],
  ['last-one-standing','Last One Standing','Memory','🏁','Track the object that remains after the others vanish.','lastOneStanding','Watch the objects disappear, then choose the last one.'],
  ['rapid-addition','Rapid Addition','Math','➕','Solve addition questions against the clock.','rapidAddition','Answer as many addition problems as you can in 15 seconds.'],
  ['rapid-subtraction','Rapid Subtraction','Math','➖','Subtract quickly without letting the timer expire.','rapidSubtraction','Answer as many subtraction problems as you can in 15 seconds.'],
  ['rapid-multiplication','Rapid Multiplication','Math','✖️','Fast multiplication with fair, clean answers.','rapidMultiplication','Answer as many multiplication problems as you can in 15 seconds.'],
  ['number-rush','Number Rush','Math','💨','Mixed arithmetic gets quicker as your streak grows.','numberRush','Solve mixed math problems before the 20-second timer ends.'],
  ['lower-number','Lower Number','Math','↘️','Choose the smaller number every time.','lowerNumber','Tap the smaller of the two numbers.'],
  ['prime-or-not','Prime or Not','Math','🔢','Separate prime numbers from composite numbers.','primeOrNot','Decide if the shown number is prime.'],
  ['missing-number','Missing Number','Math','❓','Complete a sequence with a missing middle value.','missingNumber','Find the missing number in the arithmetic sequence.'],
  ['closest-number','Closest Number','Math','🎯','Pick the number nearest to the target.','closestNumber','Choose the option with the smallest distance from the target.'],
  ['pattern-finish','Pattern Finish','Logic','🧩','Find what completes a repeating visual pattern.','patternFinish','Choose the next color in the repeating pattern.'],
  ['sequence-break','Sequence Break','Logic','🧮','Find the number that breaks the sequence rule.','sequenceBreak','Tap the one number that does not follow the pattern.'],
  ['shape-sequence','Shape Sequence','Logic','🔷','Predict the next shape in the cycle.','shapeSequence','Choose which shape comes next in the sequence.'],
  ['direction-sequence','Direction Sequence','Logic','🧭','Follow a rotating arrow pattern.','directionSequence','Tap the direction that should come next.'],
  ['logic-switch','Logic Switch','Logic','🎚️','Choose the switch that satisfies the stated rule.','logicSwitch','Select the switch that matches the rule above it.'],
  ['odd-rule','Odd Rule','Logic','🧠','Use a number rule to catch the one exception.','oddRule','Find the number that breaks the hidden rule.'],
  ['pattern-rotation','Pattern Rotation','Logic','🔄','Choose the correctly rotated tile.','patternRotation','Select the arrow rotated by the requested quarter turns.'],
  ['tile-logic','Tile Logic','Logic','🧩','Complete a small grid using its row and column rule.','tileLogic','Choose the missing tile in the 2-by-2 logic grid.'],
  ['which-comes-next','Which Comes Next?','Logic','➡️','Continue a visual sequence with one clear rule.','whichComesNext','Choose the next symbol in the sequence.'],
  ['rule-breaker','Rule Breaker','Logic','🚫','Find the symbol that violates the displayed rule.','ruleBreaker','Tap the one item that breaks the rule shown.'],
  ['dodge','Dodge!','Arcade','🛡️','Move clear of falling obstacles and survive.','dodge','Use the arrow keys or touch controls to dodge.'],
  ['catch-the-coin','Catch the Coin','Arcade','🪙','Move your catcher to collect falling coins.','catchCoin','Move left and right to catch the coins.'],
  ['avoid-the-bomb','Avoid the Bomb','Arcade','💣','Collect stars while steering clear of bombs.','avoidBomb','Collect bright stars; a bomb ends the run.'],
  ['mini-pong','Mini Pong','Arcade','🏓','Keep the bouncing ball alive with your paddle.','miniPong','Move the paddle with your pointer, arrows, or touch.'],
  ['mini-flappy','Mini Flappy','Arcade','🐤','Flap through open gaps and avoid the pipes.','miniFlappy','Tap or press Space to flap through each gap.'],
  ['jump-now','Jump Now!','Arcade','⬆️','Time your jumps over a run of obstacles.','jumpNow','Tap, click, or press Space to jump.'],
  ['lane-switch','Lane Switch','Arcade','↔️','Switch lanes to keep a clear path ahead.','laneSwitch','Use left and right to switch between three lanes.'],
  ['meteor-dodge','Meteor Dodge','Arcade','☄️','Avoid meteor waves as the pace builds.','meteorDodge','Move around the arena and stay clear of meteors.'],
  ['coin-dash','Coin Dash','Arcade','🪙','Collect a coin trail before the countdown ends.','coinDash','Move with the arrows or touch controls to collect coins.'],
  ['laser-escape','Laser Escape','Arcade','🔦','Move to a safe cell before each laser pulse.','laserEscape','Watch the warning, then move to a safe tile.'],
  ['dont-blink','Don’t Blink','Fun','👀','Keep your pointer inside the safe ring.','dontBlink','Stay inside the ring until the timer ends.'],
  ['dont-click-timer','Don’t Click','Fun','🤫','Hold off through a short, unpredictable countdown.','dontClick','Resist the button until the countdown ends.'],
  ['visual-count','Visual Count','Vision','👀','Count the highlighted objects across quick flashes.','visualCountRush','Count only the target symbol in each flash.'],
  ['lucky-number','Lucky Number','Luck','🍀','Choose a number and see how close luck gets.','luckyNumber','Pick a number from 1 to 10 before the draw.'],
  ['higher-roll','Higher Roll','Luck','🎲','Predict whether the next die roll is higher.','higherRoll','Call the next die roll higher or lower.'],
  ['impossible-button','Impossible Button','Fun','🏃','Catch a button that keeps dodging your pointer.','impossibleButton','Move your pointer or finger onto the moving button.'],
  ['how-lucky','How Lucky Are You?','Fun','🍀','A short set of luck games gives an entertainment score.','howLucky','Complete three random luck-based picks. Entertainment only.'],
  ['beat-the-ai','Beat the AI','Fun','🤖','Beat a simulated opponent in a quick choice duel.','beatAI','Choose rock, paper, or scissors against a simulated opponent.'],
  ['one-chance','One Chance','Fun','🎲','One random mini-challenge. No second attempt.','oneChance','Read the one-off challenge and make your single choice.']
];
core.push(...more);

export const categories = ['All','Reaction','Memory','Accuracy','Math','Vision','Speed','Luck','Logic','Arcade','Fun'];
export const games = core.map(([id,title,category,icon,description,mode,instructions],i)=>({id,title,category,icon,description,mode,instructions,difficulty:'Normal',accent:['#5fe5ff','#a696ff','#7ee7e4','#609bff'][i%4],featured:i<8}));
export const gameById = id => games.find(game=>game.id===id);
